// projects/plugins/boost/app/assets/src/js/elements/MoreList.svelte
<!--
	This Component shows a <ul> list with one copy of <slot> per entry in
	entries. Each slot receives an "entry" prop with its entry details.

	Automatically folds away with "...and x more" when the list exceeds showLimit.
-->
<script lang="ts">
	import { slide } from 'svelte/transition';
	import { sprintf, __ } from '@wordpress/i18n';

	/**
	 * List of objects to pass to each copy of the slot.
	 */
	export let entries: unknown[] = [];

	/**
	 * The maximum number of items to show before folding extras away.
	 */
	export let showLimit = 2;

	let expanded = false;
	function toggle() {
		expanded = ! expanded;
	}
</script>

<ul>
	{#each expanded ? entries : entries.slice( 0, showLimit ) as props}
		<li transition:slide|local>
			<slot entry={props} />
		</li>
	{/each}

	{#if ! expanded && entries.length > showLimit}
		<a on:click|preventDefault={toggle} transition:slide|local href={'#'}>
			{sprintf(
				/* translators: %d is the number of items in this list hidden behind this link */
				__( '…and %d more', 'jetpack-boost' ),
				entries.length - showLimit
			)}
		</a>
	{/if}
</ul>

// projects/plugins/boost/app/assets/src/js/features/critical-css/more-list/more-list.tsx
import { useState } from 'react';
import { sprintf, __ } from '@wordpress/i18n';
import { FormattedURL } from '../error-description/types';
import styles from './more-list.module.scss';

type MoreListTypes = {
	entries: FormattedURL[];
	showLimit?: number;
};

const MoreList: React.FC< MoreListTypes > = ( { entries = [], showLimit = 2 } ) => {
	const [ expanded, setExpanded ] = useState( false );
	const listItems = expanded ? entries : entries.slice( 0, showLimit );
	const showExpandButton = ! expanded && entries.length > showLimit;

	return (
		<>
			<ul className={ styles[ 'more-list' ] }>
				{ listItems.map( ( { href, label }, index ) => (
					<li key={ index }>
						<a href={ href } target="_blank" rel="noreferrer">
							{ label }
						</a>
					</li>
				) ) }

				{ showExpandButton && (
					<li>
						<a
							onClick={ event => {
								event.preventDefault();
								setExpanded( ! expanded );
							} }
							href="#expand"
						>
							{ sprintf(
								/* translators: %d is the number of items in this list hidden behind this link */
								__( '…and %d more', 'jetpack-boost' ),
								entries.length - showLimit
							) }
						</a>
					</li>
				) }
			</ul>
		</>
	);
};

export default MoreList;
