// projects/plugins/protect/src/js/components/progress-bar/index.jsx
import classnames from 'classnames';
import styles from './style.module.scss';

/**
 * Progress Bar component
 *
 * @param {object} props           - Component props
 * @param {string} props.className - Additional classnames
 * @param {number} props.total     - Total integer
 * @param {number} props.value     - Progress integer
 * @returns {object} ProgressBar React component.
 */
const ProgressBar = ( { className, total = 100, value } ) => {
	if ( value == null ) {
		return null;
	}

	// The percentage should not be allowed to be more than 100
	const progress = Math.min( Math.floor( ( value / total ) * 100 ), 100 );

	const style = {
		width: `${ progress }%`,
	};

	return (
		<div className={ classnames( className, styles[ 'progress-bar' ] ) }>
			<div className={ styles[ 'progress-bar__wrapper' ] }>
				<div
					aria-valuemax={ total }
					aria-valuemin={ 0 }
					aria-valuenow={ Math.min( value, total ) }
					className={ styles[ 'progress-bar__bar' ] }
					role="progressbar"
					style={ style }
				/>
			</div>
			<p className={ styles[ 'progress-bar__percent' ] }>{ `${ progress }%` }</p>
		</div>
	);
};

export default ProgressBar;

// projects/plugins/boost/app/assets/src/js/features/ui/ProgressBar.svelte
<script lang="ts">
	/**
	 * The progress bar component.
	 *
	 * @param {number} progress - The progress percentage between 0 - 100.
	 */
	export let progress: number;
</script>

<div
	role="progressbar"
	aria-valuemax={100}
	aria-valuemin={0}
	aria-valuenow={progress}
	class="jb-progress-bar"
>
	<div class="jb-progress-filler" aria-hidden="true" style={`width: ${ progress }%;`} />
</div>

<style lang="scss">
	// Basic Progress Bar styling.
	.jb-progress-bar {
		height: 20px;
		border-radius: 50px;
		background-color: #f1f1f1;
	}

	.jb-progress-filler {
		height: 100%;
		width: 0%;
		will-change: width;
		transition: width 700ms ease-in-out;
		border-radius: 50px;
		background-color: #069e08;
	}
</style>
