// projects/plugins/boost/app/assets/src/js/features/image-size-analysis/recommendations/tabs/tabs.tsx
import { useState } from 'react';
import { recordBoostEvent } from '$lib/utils/analytics';
import type { IsaCounts } from '$features/image-size-analysis';
import { useNavigate } from 'react-router-dom';
import { getGroupLabel, isaGroupKeys } from '$features/image-size-analysis/lib/isa-groups';

interface TabsProps {
	currentTab?: IsaCounts;
	activeGroupKey: string;
	imageDataGroupTabs?: Record< isaGroupKeys | string, IsaCounts >;
	setActiveTab: ( tab: isaGroupKeys ) => void;
}

const Tabs: React.FC< TabsProps > = ( {
	currentTab,
	activeGroupKey,
	imageDataGroupTabs,
	setActiveTab,
} ) => {
	const [ dropdownOpen, setDropdownOpen ] = useState( false );
	const navigate = useNavigate();
	const selectGroup = ( group: string ) => {
		navigate( `/image-size-analysis/${ group }/1` );
		setDropdownOpen( false );
	};

	const onClickDropdown = () => {
		setDropdownOpen( ! dropdownOpen );
	};
	return (
		currentTab &&
		imageDataGroupTabs &&
		activeGroupKey && (
			<div>
				<div className="jb-dropdown">
					{ /* eslint-disable-next-line jsx-a11y/click-events-have-key-events, jsx-a11y/no-static-element-interactions */ }
					<div className="jb-dropdown__head-bar" onClick={ onClickDropdown }>
						{ getGroupLabel( activeGroupKey ) }
						{ currentTab && currentTab?.issue_count > 0 && (
							<span className="jb-dropdown__issues">{ currentTab.issue_count }</span>
						) }
						<span className="dashicons dashicons-arrow-down-alt2" />
					</div>

					{ dropdownOpen && (
						<ul className="jb-dropdown__options">
							{ Object.entries( imageDataGroupTabs ).map( ( [ group, details ] ) => (
								// eslint-disable-next-line jsx-a11y/click-events-have-key-events, jsx-a11y/no-noninteractive-element-interactions
								<li
									key={ group }
									className={ `jb-dropdown__item ${ details.issue_count > 0 ? 'active' : '' } ${
										activeGroupKey === group ? 'selected' : ''
									}` }
									onClick={ () => details.issue_count > 0 && selectGroup( group ) }
								>
									{ getGroupLabel( group ) }
									<span className="jb-dropdown__issues">{ details.issue_count }</span>
								</li>
							) ) }
						</ul>
					) }
				</div>

				<div className="jb-tabs">
					{ Object.entries( imageDataGroupTabs ).map( ( [ group, details ] ) => {
						const label = getGroupLabel( group );
						const issues = details.issue_count;

						return (
							<div
								key={ group }
								className={ `jb-tab jb-tab--${ group } ${
									activeGroupKey === group ? 'active' : ''
								}` }
							>
								<div className="jb-tab__header">
									{ issues > 0 ? (
										<a
											className="jb-navigator-link"
											href={ `/image-size-analysis/${ group }/1` }
											onClick={ e => {
												e.preventDefault();
												recordBoostEvent( 'clicked_isa_report_group', { group } );
												setActiveTab( group as isaGroupKeys );
												navigate( `/image-size-analysis/${ group }/1` );
											} }
										>
											{ label }
											<span>{ issues }</span>
										</a>
									) : (
										<div className="jb-navigator-link jb-navigator-link--inactive">
											{ label }
											<span>{ issues }</span>
										</div>
									) }
								</div>
							</div>
						);
					} ) }
				</div>
			</div>
		)
	);
};

export default Tabs;

// projects/plugins/boost/app/assets/src/js/routes/image-size-analysis/recommendations/Tabs.svelte
<script lang="ts">
	import { useNavigate } from 'svelte-navigator';
	import { type ISASummaryGroup } from '../store/isa-summary';
	import { recordBoostEvent } from '$lib/utils/analytics';
	import { Link } from '$lib/utils/router';

	export let activeGroup: string;
	export let imageDataGroupTabs: Record< string, ISASummaryGroup >;
	export let isaGroupLabels;

	const navigate = useNavigate();

	let dropdownOpen = false;

	function selectGroup( group ) {
		navigate( `/image-size-analysis/${ group }/1` );
		dropdownOpen = false;
	}

	function onClickDropdown() {
		dropdownOpen = ! dropdownOpen;
	}

	$: currentTab = imageDataGroupTabs[ activeGroup ];
</script>

<div class="jb-dropdown">
	<!-- svelte-ignore a11y-click-events-have-key-events -->
	<div class="jb-dropdown__head-bar" on:click={onClickDropdown}>
		{isaGroupLabels[ activeGroup ]}
		{#if currentTab?.issue_count > 0}
			<span class="jb-dropdown__issues">{currentTab.issue_count}</span>
		{/if}
		<span class="dashicons dashicons-arrow-down-alt2" />
	</div>

	{#if dropdownOpen}
		<ul class="jb-dropdown__options">
			{#each Object.entries( imageDataGroupTabs ) as [group, details]}
				{@const ( issues = details.issue_count )}

				<!-- svelte-ignore a11y-click-events-have-key-events -->
				<li
					class:active={issues > 0}
					class:selected={activeGroup === group}
					on:click={() => issues > 0 && selectGroup( group )}
				>
					{isaGroupLabels[ group ]}
					<span class="jb-dropdown__issues">{issues}</span>
				</li>
			{/each}
		</ul>
	{/if}
</div>

<div class="jb-tabs">
	{#each Object.entries( imageDataGroupTabs ) as [group, details]}
		{@const ( label = isaGroupLabels[ group ] )}
		{@const ( issues = details.issue_count )}

		<div class="jb-tab jb-tab--{group}" class:active={activeGroup === group}>
			<div class="jb-tab__header">
				{#if issues > 0}
					<Link
						class="jb-navigator-link"
						to="/image-size-analysis/{group}/1"
						on:click={() => recordBoostEvent( 'clicked_isa_report_group', { group } )}
					>
						{label}
						<span>{issues}</span>
					</Link>
				{:else}
					<div class="jb-navigator-link jb-navigator-link--inactive">
						{label}
						<span>{issues}</span>
					</div>
				{/if}
			</div>
		</div>
	{/each}
</div>
