// projects/plugins/boost/app/assets/src/js/features/image-size-analysis/recommendations/ui/thumbnail/thumbnail.tsx
import React from 'react';

interface ThumbnailProps {
	url?: string;
	title?: string;
	width: number;
	height: number;
}

const Thumbnail: React.FC< ThumbnailProps > = ( { url, title, width, height } ) => {
	const thumbnailStyle = {
		'--thumbnail-size': `${ width }px`,
	} as React.CSSProperties;

	return url && title ? (
		<img
			src={ url }
			alt={ title }
			width={ width }
			height={ height }
			className="jb-thumbnail__image"
		/>
	) : (
		<div className="jb-thumbnail__placeholder" style={ thumbnailStyle } />
	);
};

export default Thumbnail;

// projects/plugins/boost/app/assets/src/js/features/image-size-analysis/recommendations/ui/Thumbnail.svelte
<script lang="ts">
	export let url: string;
	export let title: string;
	export let width: number;
	export let height: number;
</script>

{#if url && title}
	<img src={url} alt={title} {width} {height} class="jb-thumbnail__image" />
{:else}
	<div class="jb-thumbnail__placeholder" style:--thumbnail-size="{width}px" />
{/if}
