// projects/plugins/boost/app/assets/src/js/layout/SettingsPage/SettingsPage.svelte
<script lang="ts">
	import SpeedScore from '../../features/speed-score/speed-score';
	import Support from './support/support';
	import Tips from './Tips.svelte';
	import ReactComponent from '$features/ReactComponent.svelte';
	import Footer from '$layout/footer/footer';
	import Header from '$layout/header/header';
	import { criticalCssState, isGenerating } from '$features/critical-css';
	import { modulesState } from '$lib/stores/modules';
	import { hasPrioritySupport } from '$lib/utils/paid-plan';

	$: criticalCssCreated = $criticalCssState.created;
	$: criticalCssIsGenerating = $isGenerating;
	$: moduleStates = Object.entries( $modulesState ).reduce( ( acc, [ key, value ] ) => {
		if ( key !== 'image_guide' && key !== 'image_size_analysis' ) {
			acc.push( value.active );
		}
		return acc;
	}, [] );
	$: performanceHistoryNeedsUpgrade = ! $modulesState.performance_history.available;
</script>

<div id="jb-dashboard" class="jb-dashboard jb-dashboard--main">
	<ReactComponent this={Header} />

	<div class="jb-section jb-section--alt jp-section--scores">
		<ReactComponent
			this={SpeedScore}
			{moduleStates}
			{criticalCssCreated}
			{criticalCssIsGenerating}
			{performanceHistoryNeedsUpgrade}
		/>
	</div>

	<div class="jb-section jb-section--main">
		<slot />
	</div>

	<Tips />

	{#if $hasPrioritySupport}
		<ReactComponent this={Support} />
	{/if}

	<ReactComponent this={Footer} />
</div>

<style lang="scss">
	.jb-section--main {
		z-index: 14;
	}
</style>

// projects/plugins/boost/app/assets/src/js/layout/settings-page/settings-page.tsx
import SpeedScore from '$features/speed-score/speed-score';
import Footer from '$layout/footer/footer';
import Header from '$layout/header/header';
import { criticalCssStateCreated, isGenerating } from '$features/critical-css';
import { hasPrioritySupport } from '$lib/utils/paid-plan';
import Support from './support/support';
import Tips from './tips/tips';
import { useSingleModuleState } from '$features/module/lib/stores';
import { useEffect, useState } from 'react';
import classNames from 'classnames';
import styles from './settings-page.module.scss';

type SettingsPageProps = {
	children: React.ReactNode;
};

const SettingsPage = ( { children }: SettingsPageProps ) => {
	const [ isGeneratingValue, setIsGeneratingValue ] = useState( false );
	const [ performanceHistoryState ] = useSingleModuleState( 'performance_history' );

	useEffect( () => {
		const unsubscribe = isGenerating.subscribe( value => {
			setIsGeneratingValue( value );
		} );

		return () => {
			unsubscribe();
		};
	}, [] );

	return (
		<div id="jb-dashboard" className="jb-dashboard jb-dashboard--main">
			<Header />

			<div className="jb-section jb-section--alt jb-section--scores">
				<SpeedScore
					criticalCssCreated={ criticalCssStateCreated }
					criticalCssIsGenerating={ isGeneratingValue }
					performanceHistoryNeedsUpgrade={ ! performanceHistoryState?.available }
				/>
			</div>

			{ children && (
				<div className={ classNames( 'jb-section jb-section--main', styles.section ) }>
					{ children }
				</div>
			) }

			<Tips />

			{ hasPrioritySupport && <Support /> }

			<Footer />
		</div>
	);
};

export default SettingsPage;
