// projects/plugins/boost/app/assets/src/js/modules/image-size-analysis/recommendations/components/PaginationArrow.svelte
<script lang="ts">
	import { Link } from '../../../../utils/router';

	export let group: string;
	export let direction: 'left' | 'right';
	export let current: number;
	export let total: number;

	$: inactive = direction === 'left' ? current === 1 : current === total;
	$: page = direction === 'left' ? current - 1 : current + 1;
</script>

{#if inactive}
	<span class="jb-pagination__page jb-pagination__page--inactive">
		<slot />
	</span>
{:else}
	<Link to="/image-size-analysis/{group}/{page}" class="jb-pagination__page">
		<slot />
	</Link>
{/if}

// projects/plugins/boost/app/assets/src/js/features/image-size-analysis/recommendations/ui/pagination-arrow/pagination-arrow.tsx
import React, { useMemo } from 'react';

interface PaginationLinkProps {
	group: string;
	direction: 'left' | 'right';
	current: number;
	total: number;
	children: React.ReactNode;
}

const PaginationLink: React.FC< PaginationLinkProps > = ( {
	group,
	direction,
	current,
	total,
	children,
} ) => {
	const inactive = useMemo(
		() => ( direction === 'left' ? current === 1 : current === total ),
		[ direction, current, total ]
	);

	const page = useMemo(
		() => ( direction === 'left' ? current - 1 : current + 1 ),
		[ direction, current ]
	);

	if ( inactive ) {
		return <span className="jb-pagination__page jb-pagination__page--inactive">{ children }</span>;
	}
	return (
		<a href={ `#/image-size-analysis/${ group }/${ page }` } className="jb-pagination__page">
			{ children }
		</a>
	);
};

export default PaginationLink;
