// projects/plugins/boost/app/assets/src/js/elements/ActivateLicense.svelte
<script lang="ts">
	import { __ } from '@wordpress/i18n';
	import TemplatedString from './TemplatedString.svelte';
</script>

<p class="jb-activate-license">
	<TemplatedString
		template={__(
			'Already have an existing plan or license key? <link>Click here to get started</link>',
			'jetpack-boost'
		)}
		vars={{
			link: [
				'a',
				{
					class: 'jb-activate-license__link',
					href: 'admin.php?page=my-jetpack#/add-license',
				},
			],
		}}
	/>
</p>

<style lang="scss">
	.jb-activate-license {
		font-size: 13px;

		:global( .jb-activate-license__link ) {
			color: var( --blue-50 );

			&:hover,
			&:active {
				color: var( --blue-60 );
			}
		}
	}
</style>

// projects/plugins/boost/app/assets/src/js/components/ActivateLicense/ActivateLicense.tsx
import { createInterpolateElement } from '@wordpress/element';
import { __ } from '@wordpress/i18n';
import styles from './ActivateLicense.module.scss';

const ActivateLicense = () => {
	const activateLicenseUrl = 'admin.php?page=my-jetpack#/add-license';

	return (
		<p className={ styles[ 'activate-license' ] }>
			{ createInterpolateElement(
				__(
					'Already have an existing plan or license key? <link>Click here to get started</link>',
					'jetpack-boost'
				),
				{
					// eslint-disable-next-line jsx-a11y/anchor-has-content
					link: <a className={ styles.link } href={ activateLicenseUrl } />,
				}
			) }
		</p>
	);
};

export default ActivateLicense;
