// projects/plugins/boost/app/assets/src/js/react-components/components/minify-meta/index.tsx
import { DataSyncProvider } from '@automattic/jetpack-react-data-sync-client';
import { useEffect, useState } from 'react';
import { __, sprintf } from '@wordpress/i18n';
import { type Props, useMetaQuery, useConfig } from '../../../stores/minify';

const MetaComponent = ( { inputLabel, buttonText, placeholder, datasyncKey }: Props ) => {
	const config = useConfig();
	const [ values, updateValues ] = useMetaQuery( datasyncKey );
	const [ inputValue, setInputValue ] = useState( () => values.join( ', ' ) );
	const [ isEditing, setIsEditing ] = useState( false );

	useEffect( () => {
		setInputValue( values.join( ', ' ) );
	}, [ values ] );

	function save() {
		updateValues( inputValue );
		setIsEditing( false );
	}

	const htmlId = `jb-minify-meta-${ datasyncKey }`;

	return (
		<div className="jb-critical-css__meta">
			{ isEditing ? (
				<div className="manage-excludes">
					<label htmlFor={ htmlId }>{ inputLabel }</label>
					<input
						type="text"
						value={ inputValue }
						placeholder={ placeholder }
						id={ htmlId }
						onChange={ e => setInputValue( e.target.value ) }
					/>
					<div className="buttons-container">
						<button disabled={ values.join( ', ' ) === inputValue } onClick={ save }>
							{ __( 'Save', 'jetpack-boost' ) }
						</button>
						<button onClick={ () => setIsEditing( false ) }>
							{ __( 'Cancel', 'jetpack-boost' ) }
						</button>
					</div>
				</div>
			) : (
				<>
					<div className="summary">
						{ values.length > 0 && (
							<div className="successes">
								{ sprintf(
									/* Translators: %s refers to the list of excluded items. */
									__( 'Except: %s', 'jetpack-boost' ),
									values.join( ', ' )
								) }
							</div>
						) }
					</div>

					<button
						type="button"
						className="jb-collapsible-meta__edit-button components-button is-link"
						onClick={ () => setIsEditing( true ) }
					>
						<img
							className="edit-icon"
							src={ `${ config.plugin_dir_url }/app/assets/static/images/pencil.svg` }
							alt={ __( 'Edit', 'jetpack-boost' ) }
						/>
						{ buttonText }
					</button>
				</>
			) }
		</div>
	);
};

export default function ( props: Props ) {
	return (
		<DataSyncProvider>
			<MetaComponent { ...props } />
		</DataSyncProvider>
	);
}

// projects/plugins/boost/app/assets/src/js/pages/settings/elements/MinifyMeta.svelte
<script lang="ts" context="module">
	let nextIdIndex = 0;
</script>

<script lang="ts">
	import { createEventDispatcher } from 'svelte';
	import { __, sprintf } from '@wordpress/i18n';
	import PencilIcon from '../../../svg/pencil.svg';

	export let inputLabel: string;
	export let buttonText: string;
	export let placeholder: string;

	export let value: string[];

	let inputValue = prettyValue();
	let savedValue = inputValue;
	let isEditing = false;
	const htmlId = `minify-meta-exclude-list-${ nextIdIndex++ }`;

	const dispatch = createEventDispatcher();

	/**
	 * Helper method to format the value for display (as a comma separated list).
	 */
	function prettyValue() {
		return value.join( ', ' );
	}

	/**
	 * Save changes.
	 */
	function save() {
		// Sanitize input and save.
		value = inputValue
			.split( ',' )
			.map( v => v.trim() )
			.filter( Boolean );
		dispatch( 'save', value );
		isEditing = false;

		// Beautify the input field.
		inputValue = prettyValue();
		savedValue = inputValue;
	}

	function handleKeyPress( e ) {
		if ( savedValue !== inputValue && e.key === 'Enter' ) {
			save();
		}
	}
</script>

<div class="jb-critical-css__meta">
	{#if isEditing}
		<div class="manage-excludes">
			<label for={htmlId}>{inputLabel}</label>
			<input
				type="text"
				bind:value={inputValue}
				{placeholder}
				id={htmlId}
				on:keypress={handleKeyPress}
			/>
			<div class="buttons-container">
				<button disabled={savedValue === inputValue} on:click={save}
					>{__( 'Save', 'jetpack-boost' )}</button
				>
				<button
					on:click={() => {
						isEditing = false;
					}}>{__( 'Cancel', 'jetpack-boost' )}</button
				>
			</div>
		</div>
	{:else}
		<div class="summary">
			{#if value.length}
				<div class="successes">
					{sprintf(
						/* Translators: %s refers to the list of excluded items. */
						__( 'Except: %s', 'jetpack-boost' ),
						prettyValue()
					)}
				</div>
			{/if}
		</div>

		<button
			type="button"
			class="components-button is-link"
			on:click={() => {
				isEditing = true;
			}}
		>
			<PencilIcon />
			{buttonText}
		</button>
	{/if}
</div>
