// projects/plugins/boost/app/assets/src/js/features/image-size-analysis/progress-bar/progress-bar.tsx
import styles from './progress-bar.module.scss';

type Props = {
	progress: number;
};

const ProgressBar = ( { progress }: Props ) => {
	return (
		<div
			role="progressbar"
			aria-valuemax={ 100 }
			aria-valuemin={ 0 }
			aria-valuenow={ progress }
			className={ styles.bar }
		>
			<div className={ styles.filler } aria-hidden="true" style={ { width: `${ progress }%` } } />
		</div>
	);
};

export default ProgressBar;

// projects/plugins/boost/app/assets/src/js/pages/settings/elements/ProgressBar.svelte
<script>
	import { criticalCssStatus } from '../../../stores/critical-css-status';

	export let progress = 0;
</script>

<div
	role="progressbar"
	aria-valuemax="100"
	aria-valuemin="0"
	aria-valuenow={progress}
	class="jb-progress-bar"
>
	<div class="jb-progress-bar__filler" aria-hidden="true" style={`width: ${ progress }%;`} />
</div>
