// projects/plugins/boost/app/assets/src/js/pages/image-size-analysis/image-size-analysis.tsx
import { __ } from '@wordpress/i18n';
import {
	Hero,
	Pagination,
	Table,
	Tabs,
	getGroupedReports,
	useIsaData,
	useIsaReport,
} from '$features/image-size-analysis';
import Footer from '../../layout/footer/footer';
import Header from '../../layout/header/header';
import { DataSyncProvider } from '@automattic/jetpack-react-data-sync-client';

const _ImageSizeAnalysis = ( { isImageCdnModuleActive }: { isImageCdnModuleActive: boolean } ) => {
	const [ isaData ] = useIsaData();
	const [ isaReport ] = useIsaReport();
	const dataGroupTabs = isaReport.data ? getGroupedReports( isaReport.data ) : undefined;
	const activeGroupName = isaData.data?.query.group as keyof typeof dataGroupTabs;
	const activeReport =
		dataGroupTabs && activeGroupName ? dataGroupTabs[ activeGroupName ] : undefined;

	return (
		<div id="jb-dashboard" className="jb-dashboard">
			<Header subPageTitle={ __( 'Image analysis report', 'jetpack-boost' ) } />
			<div className="jb-recommendations-page jb-section--alt">
				<div className="jb-container">
					<Hero
						isImageCdnModuleActive={ isImageCdnModuleActive }
						isaLastUpdated={ isaData.data?.data.last_updated || 0 }
						group={ activeReport }
					/>
					<Tabs
						currentTab={ activeReport }
						activeGroupKey={ isaData.data?.query.group }
						imageDataGroupTabs={ dataGroupTabs }
					/>
				</div>

				<div className="jb-table-wrap">
					<Table
						isaDataLoading={ isaData.isLoading }
						activeGroup={ isaData.data?.query.group }
						images={ isaData.data?.data.images || [] }
						isaReport={ isaReport.data || undefined }
					/>
				</div>

				<div className="jb-container">
					<Pagination
						group={ isaData.data?.query.group || 'all' }
						current={ isaData.data?.query.page || 1 }
						total={ isaData.data?.data.total_pages || 1 }
					/>
					<Footer />
				</div>
			</div>
		</div>
	);
};

const ImageSizeAnalysis = ( { isImageCdnModuleActive }: { isImageCdnModuleActive: boolean } ) => {
	return (
		<DataSyncProvider>
			<_ImageSizeAnalysis isImageCdnModuleActive={ isImageCdnModuleActive } />
		</DataSyncProvider>
	);
};
export default ImageSizeAnalysis;

// projects/plugins/boost/app/assets/src/js/routes/image-size-analysis/ImageSizeAnalysis.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { get } from 'svelte/store';
	import { __ } from '@wordpress/i18n';
	import ReactComponent from '$features/ReactComponent.svelte';
	import { Hero } from '$features/image-size-analysis/Hero/Hero';
	import Pagination from '$features/image-size-analysis/recommendations/Pagination.svelte';
	import Table from '$features/image-size-analysis/recommendations/Table.svelte';
	import Tabs from '$features/image-size-analysis/recommendations/Tabs.svelte';
	import {
		initializeIsaData,
		isaData,
		isaDataLoading,
		refreshIsaData,
	} from '$features/image-size-analysis/store/isa-data';
	import {
		isaGroupLabels,
		imageDataActiveGroup,
		imageDataGroupTabs,
		initializeIsaSummary,
		totalIssueCount,
		isaSummary,
	} from '$features/image-size-analysis/store/isa-summary';
	import Footer from '$layout/Footer/Footer';
	import Header from '$layout/Header/Header';
	import { modulesState } from '$lib/stores/modules';

	initializeIsaData();

	onMount( () => {
		initializeIsaSummary();
	} );

	// Keep track of the total count from the summary the last time we got a data update.
	// Useful for identify when a summary change might mean we need a refresh.
	let countAtLastDataUpdate = 0;
	isaData.subscribe( () => {
		countAtLastDataUpdate = get( totalIssueCount );
	} );

	$: needsRefresh = $totalIssueCount > countAtLastDataUpdate;
	$: isImageCdnModuleActive = $modulesState.image_cdn.active;
	$: isaLastUpdated = $isaData.data.last_updated;
	$: hasActiveGroup = !! $imageDataActiveGroup;
	$: images = $isaData.data.images;
	$: activeGroup = $isaData.query.group;
	$: issueCount = $totalIssueCount;
	$: dataLoading = $isaDataLoading;
	$: summary = $isaSummary;
	$: dataGroupTabs = $imageDataGroupTabs;

	async function refresh() {
		// Don't let the UI show a refresh button until we get fresh ISA data.
		countAtLastDataUpdate = Infinity;
		await refreshIsaData();
	}
</script>

<div id="jb-dashboard" class="jb-dashboard">
	<ReactComponent this={Header} subPageTitle={__( 'Image analysis report', 'jetpack-boost' )} />
	<div class="jb-recommendations-page jb-section--alt">
		<div class="jb-container">
			<ReactComponent
				this={Hero}
				{needsRefresh}
				{refresh}
				{isImageCdnModuleActive}
				{isaLastUpdated}
				{hasActiveGroup}
				totalIssueCount={issueCount}
			/>
			<Tabs {activeGroup} imageDataGroupTabs={dataGroupTabs} {isaGroupLabels} />
		</div>

		<div class="jb-table-wrap">
			<Table
				{needsRefresh}
				{refresh}
				isaDataLoading={dataLoading}
				{activeGroup}
				{images}
				isaSummary={summary}
			/>
		</div>

		<div class="jb-container">
			<Pagination
				group={$isaData.query.group}
				current={$isaData.query.page}
				total={$isaData.data.total_pages}
			/>
			<ReactComponent this={Footer} />
		</div>
	</div>
</div>
