// projects/plugins/boost/app/assets/src/js/features/image-size-analysis/recommendations-meta/recommendations-meta.tsx
import { useState, useEffect } from 'react';
import { __, sprintf } from '@wordpress/i18n';
import MultiProgress from '../multi-progress/multi-progress';
import Button from '../button/button';
import { requestImageAnalysis, ISAStatus, getSummaryProgress } from '../lib/stores/isa-summary';
import { resetIsaQuery } from '../lib/stores/isa-data';
import ErrorNotice from '$features/error-notice/error-notice';
import ImageCdnRecommendation from '$features/image-size-analysis/image-cdn-recommendation/image-cdn-recommendation';
import { recordBoostEvent, recordBoostEventAndRedirect } from '$lib/utils/analytics';
import getIsaErrorSuggestion from '$lib/utils/get-isa-error-suggestion';
import RefreshIcon from '$svg/refresh';
import WarningIcon from '$svg/warning-outline';
import type { ISASummaryGroup, ISASummary } from '../lib/stores/isa-summary';

interface RecommendationsMetaProps {
	isCdnActive: boolean;
	isaSummary: ISASummary | null;
}

const RecommendationsMeta: React.FC< RecommendationsMetaProps > = ( {
	isCdnActive,
	isaSummary,
} ) => {
	const [ requestingReport, setRequestingReport ] = useState< boolean >( false );
	const [ errorCode, setErrorCode ] = useState< number | undefined >( undefined );
	const [ status, setStatus ] = useState< ISAStatus | undefined >( undefined );
	const [ groups, setGroups ] = useState< Record< string, ISASummaryGroup > >( {} );
	const [ scannedPages, setScannedPages ] = useState< number >( 0 );
	const [ totalIssues, setTotalIssues ] = useState< number >( 0 );
	const [ errorMessage, setErrorMessage ] = useState< string | undefined >( undefined );
	const [ errorSuggestion, setErrorSuggestion ] = useState< string | undefined >( undefined );
	const [ waitNotice, setWaitNotice ] = useState< string | undefined >( undefined );
	const [ showCDNRecommendation, setShowCDNRecommendation ] = useState< boolean >( false );

	useEffect( () => {
		setStatus( isaSummary?.status );
		setGroups( isaSummary?.groups || {} );
		setScannedPages( scannedPagesCount( isaSummary?.groups || {} ) );
		/**
		 * Calculate total number of issues.
		 */
		setTotalIssues(
			Object.values( isaSummary?.groups || {} ).reduce(
				( total, group ) => total + group.issue_count,
				0
			)
		);
		/**
		 * Work out if there is an error to show in the UI.
		 */
		setErrorMessage( getErrorMessage( undefined, status ) );
		/**
		 * Update suggestion based on error code.
		 */
		setErrorSuggestion( getIsaErrorSuggestion( errorCode ) );
		/**
		 * Work out whether we have a 'give us a minute' notice to show.
		 */
		setWaitNotice( getWaitNotice( requestingReport, status ) );
		setShowCDNRecommendation(
			! isCdnActive && ( totalIssues > 0 || status === ISAStatus.NotFound )
		);
	}, [ isCdnActive, isaSummary, errorCode, requestingReport, status, totalIssues ] );

	const scannedPagesCount = ( isaGroups: Record< string, ISASummaryGroup > ) => {
		return Object.values( isaGroups )
			.map( group => group.scanned_pages )
			.reduce( ( a, b ) => a + b, 0 );
	};

	const getErrorMessage = (
		error: string | undefined,
		currentStatus: string | false | undefined
	) => {
		return (
			error ||
			( currentStatus === ISAStatus.Stuck &&
				__(
					'Your Image Size Analysis task seems to have gotten stuck, or our system is under unusual load. Please try again. If the issue persists, please contact support.',
					'jetpack-boost'
				) )
		);
	};

	const getWaitNotice = ( isRequesting: boolean, currentStatus: string | undefined ) => {
		if ( isRequesting ) {
			return __( 'Getting ready…', 'jetpack-boost' );
		}
		if ( currentStatus === ISAStatus.New ) {
			return __( 'Warming up the engine…', 'jetpack-boost' );
		}
		if ( currentStatus === ISAStatus.Queued ) {
			return __( 'Give us a few minutes while we go through your images…', 'jetpack-boost' );
		}
		return undefined;
	};

	/**
	 * Start a new image analysis job.
	 */
	const startAnalysis = async () => {
		try {
			setErrorCode( undefined );
			setErrorMessage( undefined );
			setRequestingReport( true );
			await requestImageAnalysis();
			resetIsaQuery();
		} catch ( err ) {
			setErrorCode( err.body?.code );
			setErrorMessage( err.message );
		} finally {
			setRequestingReport( false );
		}
	};

	const handleAnalyzeClick = () => {
		const eventName =
			status === ISAStatus.Completed
				? 'clicked_restart_isa_on_summary_page'
				: 'clicked_start_isa_on_summary_page';
		recordBoostEvent( eventName, {} );
		return startAnalysis();
	};

	return (
		<div>
			{ ! groups ? (
				<div className="jb-summary">{ __( 'Loading…', 'jetpack-boost' ) }</div>
			) : (
				<>
					{ errorMessage ? (
						<div className="jb-error-area">
							<ErrorNotice
								title={ __( 'Something has gone wrong.', 'jetpack-boost' ) }
								suggestion={ errorSuggestion }
								error={ errorMessage }
							/>
						</div>
					) : waitNotice ? (
						<div className="jb-summary-line jb-wait-notice">{ waitNotice }</div>
					) : null }

					{ ! requestingReport && status === ISAStatus.Completed && (
						<div className="jb-summary-line">
							{ totalIssues > 0 ? (
								<div className="jb-has-issues jb-summary">
									<WarningIcon />
									{ sprintf(
										// translators: 1: Number of scanned issues found 2: Number of scanned pages
										__(
											'Found a total of %1$d issues after scanning your %2$d most recent pages.',
											'jetpack-boost'
										),
										totalIssues,
										scannedPages
									) }
								</div>
							) : (
								<div className="jb-summary">
									{ sprintf(
										// translators: %d: Number of pages scanned
										__(
											'Congratulations; no issues found after scanning your %d most recent pages.',
											'jetpack-boost'
										),
										scannedPages
									) }
								</div>
							) }
							<button
								type="button"
								className="components-button is-link"
								onClick={ handleAnalyzeClick }
								disabled={ requestingReport }
							>
								<RefreshIcon />
								{ __( 'Analyze again', 'jetpack-boost' ) }
							</button>
						</div>
					) }

					{ ! requestingReport &&
						status &&
						[ ISAStatus.Completed, ISAStatus.Queued ].includes( status ) && (
							<MultiProgress summaryProgress={ getSummaryProgress( groups ) } />
						) }

					{ showCDNRecommendation && (
						<div className="jb-notice">
							<div className="jb-notice__content">
								<ImageCdnRecommendation />
							</div>
						</div>
					) }

					{ status &&
						[ ISAStatus.Queued, ISAStatus.Completed ].includes( status ) &&
						! requestingReport && (
							<div className="jb-button-area">
								<Button
									disabled={ requestingReport }
									onClick={ () =>
										recordBoostEventAndRedirect(
											'#image-size-analysis/all/1',
											'clicked_view_isa_report_on_summary_page',
											{}
										)
									}
								>
									{ ( status as ISAStatus ) === ISAStatus.Completed
										? __( 'See full report', 'jetpack-boost' )
										: __( 'View report in progress', 'jetpack-boost' ) }
								</Button>
							</div>
						) }

					{ ( ! status ||
						! [ ISAStatus.New, ISAStatus.Queued, ISAStatus.Completed ].includes( status ) ) && (
						<div className="jb-button-area">
							<Button disabled={ requestingReport } onClick={ handleAnalyzeClick }>
								{ status === ISAStatus.Completed
									? __( 'Analyze again', 'jetpack-boost' )
									: __( 'Start image analysis', 'jetpack-boost' ) }
							</Button>
						</div>
					) }
				</>
			) }
		</div>
	);
};

export default RecommendationsMeta;

// projects/plugins/boost/app/assets/src/js/routes/image-size-analysis/RecommendationsMeta.svelte
<script lang="ts">
	import { __, sprintf } from '@wordpress/i18n';
	import MultiProgress from './MultiProgress.svelte';
	import Button from './components/Button.svelte';
	import { resetIsaQuery } from './store/isa-data';
	import {
		requestImageAnalysis,
		ISAStatus,
		getSummaryProgress,
		type ISASummaryGroup,
		type ISASummary,
	} from './store/isa-summary';
	import ErrorNotice from '$features/ErrorNotice.svelte';
	import ImageCdnRecommendation from '$features/ImageCdnRecommendation/ImageCdnRecommendation';
	import ReactComponent from '$features/ReactComponent.svelte';
	import { recordBoostEvent, recordBoostEventAndRedirect } from '$lib/utils/analytics';
	import getIsaErrorSuggestion from '$lib/utils/get-isa-error-suggestion';
	import RefreshIcon from '$svg/refresh.svg';
	import WarningIcon from '$svg/warning-outline.svg';

	export let isCdnActive: boolean;
	export let isaSummary: ISASummary | null;

	function scannedPagesCount( isaGroups: Record< string, ISASummaryGroup > ) {
		return Object.values( isaGroups )
			.map( group => group.scanned_pages )
			.reduce( ( a, b ) => a + b, 0 );
	}

	let submitError: undefined | string;
	let requestingReport = false;
	let errorCode: undefined | number;

	$: status = isaSummary?.status;
	$: groups = isaSummary?.groups || {};
	$: scannedPages = scannedPagesCount( groups );

	/**
	 * Calculate total number of issues.
	 */
	$: totalIssues = groups
		? Object.values( groups ).reduce( ( total, group ) => total + group.issue_count, 0 )
		: 0;

	/**
	 * Work out if there is an error to show in the UI.
	 */
	$: errorMessage =
		submitError ||
		( status === ISAStatus.Stuck &&
			__(
				'Your Image Size Analysis task seems to have gotten stuck, or our system is under unusual load. Please try again. If the issue persists, please contact support.',
				'jetpack-boost'
			) );

	/**
	 * Update suggestion based on error code.
	 */
	$: errorSuggestion = getIsaErrorSuggestion( errorCode );

	/**
	 * Work out whether we have a 'give us a minute' notice to show.
	 */
	$: waitNotice =
		( requestingReport && __( 'Getting ready…', 'jetpack-boost' ) ) ||
		( status === ISAStatus.New && __( 'Warming up the engine…', 'jetpack-boost' ) ) ||
		( status === ISAStatus.Queued &&
			__( 'Give us a few minutes while we go through your images…', 'jetpack-boost' ) );

	/**
	 * Start a new image analysis job.
	 */
	async function startAnalysis() {
		try {
			errorCode = undefined;
			errorMessage = undefined;
			requestingReport = true;
			await requestImageAnalysis();
			resetIsaQuery();
		} catch ( err ) {
			errorCode = err.body?.code;
			errorMessage = err.message;
		} finally {
			requestingReport = false;
		}
	}

	function handleAnalyzeClick() {
		const eventName =
			status === ISAStatus.Completed
				? 'clicked_restart_isa_on_summary_page'
				: 'clicked_start_isa_on_summary_page';
		recordBoostEvent( eventName, {} );
		return startAnalysis();
	}

	/**
	 * Work out whether to recommend the Image CDN. It should show if the CDN is off and no report has been run, or a report has found issues.
	 */
	$: showCDNRecommendation = ! isCdnActive && ( totalIssues > 0 || status === ISAStatus.NotFound );
</script>

{#if ! groups}
	<div class="jb-summary">
		{__( 'Loading…', 'jetpack-boost' )}
	</div>
{:else}
	<!-- Show error messages or "please wait" messages. -->
	{#if errorMessage}
		<div class="jb-error-area">
			<ErrorNotice
				title={__( 'Something has gone wrong.', 'jetpack-boost' )}
				suggestion={errorSuggestion}
			>
				{errorMessage}
			</ErrorNotice>
		</div>
	{:else if waitNotice}
		<div class="jb-summary-line jb-wait-notice">
			{waitNotice}
		</div>
	{/if}

	<!-- Show a summary line if the report is completed. -->
	{#if ! requestingReport && status === ISAStatus.Completed}
		<div class="jb-summary-line">
			{#if totalIssues > 0}
				<div class="jb-has-issues jb-summary">
					<WarningIcon />
					{sprintf(
						// translators: 1: Number of scanned issues found 2: Number of scanned pages
						__(
							'Found a total of %1$d issues after scanning your %2$d most recent pages.',
							'jetpack-boost'
						),
						totalIssues,
						scannedPages
					)}
				</div>
			{:else}
				<div class="jb-summary">
					{sprintf(
						// translators: %d: Number of pages scanned
						__(
							'Congratulations; no issues found after scanning your %d most recent pages.',
							'jetpack-boost'
						),
						scannedPages
					)}
				</div>
			{/if}

			<button
				type="button"
				class="components-button is-link"
				on:click={handleAnalyzeClick}
				disabled={requestingReport}
			>
				<RefreshIcon />
				{__( 'Analyze again', 'jetpack-boost' )}
			</button>
		</div>
	{/if}

	<!-- Show progress if a job is rolling. -->
	{#if ! requestingReport && [ ISAStatus.Completed, ISAStatus.Queued ].includes( status )}
		<MultiProgress summaryProgress={getSummaryProgress( groups )} />
	{/if}

	<!-- Show recommendation to enable Image CDN if it was inactive and issues have been found -->
	{#if showCDNRecommendation}
		<div class="jb-notice">
			<div class="jb-notice__content">
				<ReactComponent this={ImageCdnRecommendation} />
			</div>
		</div>
	{/if}

	<!-- Show a button to view the report if it's in progress or completed. -->
	{#if [ ISAStatus.Queued, ISAStatus.Completed ].includes( status ) && ! requestingReport}
		<div class="jb-button-area">
			<Button
				disabled={requestingReport}
				on:click={() =>
					recordBoostEventAndRedirect(
						'#image-size-analysis/all/1',
						'clicked_view_isa_report_on_summary_page',
						{}
					)}
			>
				{status === ISAStatus.Completed
					? __( 'See full report', 'jetpack-boost' )
					: __( 'View report in progress', 'jetpack-boost' )}
			</Button>
		</div>
	{/if}

	<!-- Show a button to kick off a report -->
	{#if ! [ ISAStatus.New, ISAStatus.Queued, ISAStatus.Completed ].includes( status )}
		<div class="jb-button-area">
			<Button disabled={requestingReport} on:click={handleAnalyzeClick}>
				{status === ISAStatus.Completed
					? __( 'Analyze again', 'jetpack-boost' )
					: __( 'Start image analysis', 'jetpack-boost' )}
			</Button>
		</div>
	{/if}
{/if}
