// projects/plugins/boost/app/assets/src/js/pages/index/index.tsx
import CriticalCssMeta from '$features/critical-css/critical-css-meta/critical-css-meta';
import { useSingleModuleState } from '$features/module/lib/stores';
import Module from '$features/module/module';
import UpgradeCTA from '$features/upgrade-cta/upgrade-cta';
import { Notice, getRedirectUrl } from '@automattic/jetpack-components';
import { createInterpolateElement } from '@wordpress/element';
import { __ } from '@wordpress/i18n';
import { usePremiumFeatures } from '$lib/stores/premium-features';
import CloudCssMeta from '$features/critical-css/cloud-css-meta/cloud-css-meta';
import MinifyMeta from '$features/minify-meta/minify-meta';
import { QualitySettings } from '$features/image-cdn';
import styles from './index.module.scss';
import { RecommendationsMeta } from '$features/image-size-analysis';
import SuperCacheInfo from '$features/super-cache-info/super-cache-info';
import { useRegenerateCriticalCssAction } from '$features/critical-css/lib/stores/critical-css-state';
import PremiumTooltip from '$features/premium-tooltip/premium-tooltip';
import Upgraded from '$features/ui/upgraded/upgraded';

const Index = () => {
	const criticalCssLink = getRedirectUrl( 'jetpack-boost-critical-css' );
	const deferJsLink = getRedirectUrl( 'jetpack-boost-defer-js' );

	const [ isaState ] = useSingleModuleState( 'image_size_analysis' );
	const [ imageCdn ] = useSingleModuleState( 'image_cdn' );

	const regenerateCssAction = useRegenerateCriticalCssAction();
	const requestRegenerateCriticalCss = () => {
		regenerateCssAction.mutate();
	};
	const { canResizeImages } = Jetpack_Boost;

	const premiumFeatures = usePremiumFeatures();
	const isPremium = premiumFeatures.length > 0;

	return (
		<div className="jb-container--narrow">
			<Module
				slug="critical_css"
				title={ __( 'Optimize Critical CSS Loading (manual)', 'jetpack-boost' ) }
				onEnable={ requestRegenerateCriticalCss }
				description={
					<>
						<p>
							{ createInterpolateElement(
								__(
									`Move important styling information to the start of the page, which helps pages display your content sooner, so your users don’t have to wait for the entire page to load. Commonly referred to as <link>Critical CSS</link>.`,
									'jetpack-boost'
								),
								{
									// eslint-disable-next-line jsx-a11y/anchor-has-content
									link: <a href={ criticalCssLink } target="_blank" rel="noopener noreferrer" />,
								}
							) }
						</p>
						<div className={ styles[ 'tooltip-wrapper' ] }>
							<p>
								{ createInterpolateElement(
									__(
										`<b>You should regenerate your Critical CSS</b> whenever you make changes to the HTML or CSS structure of your site.`,
										'jetpack-boost'
									),
									{
										b: <b />,
									}
								) }
							</p>
							<PremiumTooltip />
						</div>
					</>
				}
			>
				<CriticalCssMeta />

				<UpgradeCTA
					description={ __(
						'Save time by upgrading to Automatic Critical CSS generation.',
						'jetpack-boost'
					) }
				/>
			</Module>
			<Module
				slug="cloud_css"
				title={
					<>
						{ __( 'Automatically Optimize CSS Loading', 'jetpack-boost' ) }
						<Upgraded />
					</>
				}
				onEnable={ requestRegenerateCriticalCss }
				description={
					<>
						<p>
							{ createInterpolateElement(
								__(
									`Move important styling information to the start of the page, which helps pages display your content sooner, so your users don’t have to wait for the entire page to load. Commonly referred to as <link>Critical CSS</link>.`,
									'jetpack-boost'
								),
								{
									// eslint-disable-next-line jsx-a11y/anchor-has-content
									link: <a href={ criticalCssLink } target="_blank" rel="noopener noreferrer" />,
								}
							) }
						</p>
						<p>
							{ createInterpolateElement(
								__(
									`<b>Boost will automatically generate your Critical CSS</b> whenever you make changes to the HTML or CSS structure of your site.`,
									'jetpack-boost'
								),
								{
									b: <strong />,
								}
							) }
						</p>
					</>
				}
			>
				<CloudCssMeta />
			</Module>
			<Module
				slug="render_blocking_js"
				title={ __( 'Defer Non-Essential JavaScript', 'jetpack-boost' ) }
				description={
					<p>
						{ createInterpolateElement(
							__(
								`Run non-essential JavaScript after the page has loaded so that styles and images can load more quickly. Read more on <link>web.dev</link>.`,
								'jetpack-boost'
							),
							{
								// eslint-disable-next-line jsx-a11y/anchor-has-content
								link: <a href={ deferJsLink } target="_blank" rel="noopener noreferrer" />,
							}
						) }
					</p>
				}
			></Module>
			<Module
				slug="minify_js"
				title={ __( 'Concatenate JS', 'jetpack-boost' ) }
				description={
					<p>
						{ __(
							'Scripts are grouped by their original placement, concatenated and minified to reduce site loading time and reduce the number of requests.',
							'jetpack-boost'
						) }
					</p>
				}
			>
				<MinifyMeta
					datasyncKey="minify_js_excludes"
					inputLabel={ __( 'Exclude JS Strings:', 'jetpack-boost' ) }
					buttonText={ __( 'Exclude JS Strings', 'jetpack-boost' ) }
					placeholder={ __( 'Comma separated list of JS scripts to exclude', 'jetpack-boost' ) }
				/>
			</Module>
			<Module
				slug="minify_css"
				title={ __( 'Concatenate CSS', 'jetpack-boost' ) }
				description={
					<p>
						{ __(
							'Styles are grouped by their original placement, concatenated and minified to reduce site loading time and reduce the number of requests.',
							'jetpack-boost'
						) }
					</p>
				}
			>
				<MinifyMeta
					datasyncKey="minify_css_excludes"
					inputLabel={ __( 'Exclude CSS Strings:', 'jetpack-boost' ) }
					buttonText={ __( 'Exclude CSS Strings', 'jetpack-boost' ) }
					placeholder={ __(
						'Comma separated list of CSS stylesheets to exclude',
						'jetpack-boost'
					) }
				/>
			</Module>
			<Module
				slug="image_cdn"
				title={ __( 'Image CDN', 'jetpack-boost' ) }
				description={
					<p>
						{ __(
							`Deliver images from Jetpack's Content Delivery Network. Automatically resizes your images to an appropriate size, converts them to modern efficient formats like WebP, and serves them from a worldwide network of servers.`,
							'jetpack-boost'
						) }
					</p>
				}
			>
				<QualitySettings isPremium={ isPremium } />
			</Module>

			<div className={ styles.settings }>
				<Module
					slug="image_guide"
					title={
						<>
							{ __( 'Image Guide', 'jetpack-boost' ) }
							<span className={ styles.beta }>Beta</span>
						</>
					}
					description={
						<>
							<p>
								{ __(
									`This feature helps you discover images that are too large. When you browse your site, the image guide will show you an overlay with information about each image's size.`,
									'jetpack-boost'
								) }
							</p>
							{ ! isaState?.available && (
								<UpgradeCTA
									description={ __(
										'Upgrade to scan your site for issues - automatically!',
										'jetpack-boost'
									) }
								/>
							) }
						</>
					}
				>
					{ false === canResizeImages && (
						<Notice
							level="warning"
							title={ __( 'Image resizing is unavailable', 'jetpack-boost' ) }
							hideCloseButton={ true }
						>
							<p>
								{ __(
									"It looks like your server doesn't have Imagick or GD extensions installed.",
									'jetpack-boost'
								) }
							</p>
							<p>
								{ __(
									"Jetpack Boost is able to work without these extensions, but it's likely that it's going to be difficult for you to optimize the images that the Image Guide will identify without one of these extensions.",
									'jetpack-boost'
								) }
							</p>
							<p>
								{ __(
									'Please contact your hosting provider or system administrator and ask them to install or activate one of these extensions.',
									'jetpack-boost'
								) }
							</p>
						</Notice>
					) }
				</Module>

				<Module
					slug="image_size_analysis"
					toggle={ false }
					title={
						<>
							{ __( 'Image Size Analysis', 'jetpack-boost' ) }
							<span className={ styles.beta }>Beta</span>
						</>
					}
					description={
						<p>
							{ __(
								`This tool will search your site for images that are too large and have an impact on your visitors' experience, page loading times, and search rankings. Once finished, it will give you a report of all improperly sized images with suggestions on how to fix them.`,
								'jetpack-boost'
							) }
						</p>
					}
				>
					{ isaState?.active && <RecommendationsMeta isCdnActive={ !! imageCdn?.active } /> }
				</Module>
			</div>

			<SuperCacheInfo />
		</div>
	);
};

export default Index;

// projects/plugins/boost/app/assets/src/js/routes/index/Index.svelte
<script lang="ts" context="module">
	let alreadyResumed = false;
</script>

<script lang="ts">
	import { getRedirectUrl } from '@automattic/jetpack-components';
	import { onMount } from 'svelte';
	import { __ } from '@wordpress/i18n';
	import RecommendationsMeta from '$features/image-size-analysis/RecommendationsMeta.svelte';
	import {
		initializeIsaSummary,
		isaSummary,
	} from '$features/image-size-analysis/store/isa-summary';
	import Notice from '$features/Notice.svelte';
	import ReactComponent from '$features/ReactComponent.svelte';
	import TemplatedString from '$features/TemplatedString.svelte';
	import CloudCssMeta from '$features/critical-css/CloudCssMeta.svelte';
	import CriticalCssMeta from '$features/critical-css/CriticalCssMeta.svelte';
	import ImageCdnQualitySettings from '$features/image-cdn/ImageCdnQualitySettings.svelte';
	import MinifyMeta from '$features/minify-meta/minify-meta';
	import Module from '$features/modules/Module.svelte';
	import PremiumTooltip from '$features/modules/PremiumTooltip.svelte';
	import { RegenerateCriticalCssSuggestion } from '$features/critical-css/RegenerateCriticalCssSuggestion/RegenerateCriticalCssSuggestion';
	import ResizingUnavailable from './ResizingUnavailable.svelte';
	import SuperCacheInfo from '$features/modules/SuperCacheInfo.svelte';
	import UpgradeCTA from '$features/modules/UpgradeCTA.svelte';
	import config from '$lib/stores/config';
	import {
		criticalCssState,
		continueGeneratingLocalCriticalCss,
		regenerateCriticalCss,
		criticalCssProgress,
		isFatalError,
	} from '$lib/stores/critical-css-state';
	import { criticalCssIssues, primaryErrorSet } from '$lib/stores/critical-css-state-errors';
	import { suggestRegenerateDS } from '$lib/stores/data-sync-client';
	import { imageCdnQuality } from '$features/image-cdn/store';
	import { modulesState } from '$lib/stores/modules';
	import { premiumFeatures } from '$lib/stores/premium-features';
	import { startPollingCloudStatus, stopPollingCloudCssStatus } from '$lib/utils/cloud-css';
	import externalLinkTemplateVar from '$lib/utils/external-link-template-var';

	const criticalCssLink = getRedirectUrl( 'jetpack-boost-critical-css' );
	const deferJsLink = getRedirectUrl( 'jetpack-boost-defer-js' );
	const lazyLoadLink = getRedirectUrl( 'jetpack-boost-lazy-load' );
	const learnLazyLoadDeprecation = () => {
		window.open( getRedirectUrl( 'jetpack-boost-lazy-load-deprecation' ), '_blank' );
	};

	$: lazyLoadDeprecationMessage = $modulesState.lazy_images?.available
		? __(
				'Modern browsers now support lazy loading, and WordPress itself bundles lazy loading for images. This feature will consequently be removed from Jetpack Boost.',
				'jetpack-boost'
		  )
		: __(
				'Modern browsers now support lazy loading, and WordPress itself bundles lazy loading for images. This feature has been disabled to avoid potential conflicts with Gutenberg 16.6.0+ or WordPress 6.4+. This feature will consequently be removed from Jetpack Boost.',
				'jetpack-boost'
		  );

	const suggestRegenerate = suggestRegenerateDS.store;

	$: yearlyPricing = $config.pricing.yearly;

	async function resume() {
		if ( alreadyResumed ) {
			return;
		}
		alreadyResumed = true;

		if ( ! $criticalCssState || $criticalCssState.status === 'not_generated' ) {
			return regenerateCriticalCss();
		}
		await continueGeneratingLocalCriticalCss( $criticalCssState );
	}

	onMount( () => {
		if ( $modulesState.image_size_analysis.active ) {
			initializeIsaSummary();
		}
	} );
</script>

<div class="jb-container--narrow">
	<Module
		slug="critical_css"
		on:enabled={resume}
		on:mountEnabled={resume}
		on:disabled={() => ( alreadyResumed = false )}
	>
		<h3 slot="title">
			{__( 'Optimize Critical CSS Loading (manual)', 'jetpack-boost' )}
		</h3>

		<div slot="description">
			<p>
				<TemplatedString
					template={__(
						`Move important styling information to the start of the page, which helps pages display your content sooner, so your users don’t have to wait for the entire page to load. Commonly referred to as <link>Critical CSS</link>.`,
						'jetpack-boost'
					)}
					vars={externalLinkTemplateVar( criticalCssLink )}
				/>
			</p>

			<p>
				<TemplatedString
					template={__(
						`<b>You should regenerate your Critical CSS</b> whenever you make changes to the HTML or CSS structure of your site.`,
						'jetpack-boost'
					)}
					vars={{
						b: [ 'strong', {}, '' ],
					}}
				/>

				<PremiumTooltip />
			</p>
		</div>

		<div slot="meta">
			<CriticalCssMeta
				cssState={$criticalCssState}
				isCloudCssAvailable={$modulesState.cloud_css?.available}
				criticalCssProgress={$criticalCssProgress}
				issues={$criticalCssIssues}
				isFatalError={$isFatalError}
				primaryErrorSet={$primaryErrorSet}
				suggestRegenerate={$suggestRegenerate}
				{regenerateCriticalCss}
			/>
		</div>

		<div slot="notice">
			<ReactComponent
				this={RegenerateCriticalCssSuggestion}
				show={$suggestRegenerate && $criticalCssState.status !== 'pending'}
				type={$suggestRegenerate}
			/>
		</div>

		<svelte:fragment slot="cta">
			<UpgradeCTA
				description={__(
					'Save time by upgrading to Automatic Critical CSS generation.',
					'jetpack-boost'
				)}
				{yearlyPricing}
			/>
		</svelte:fragment>
	</Module>

	<Module
		slug="cloud_css"
		on:enabled={startPollingCloudStatus}
		on:disabled={stopPollingCloudCssStatus}
		on:mountEnabled={startPollingCloudStatus}
	>
		<h3 slot="title">
			{__( 'Automatically Optimize CSS Loading', 'jetpack-boost' )}
			<span class="jb-badge">Upgraded</span>
		</h3>
		<div slot="description">
			<p>
				<TemplatedString
					template={__(
						`Move important styling information to the start of the page, which helps pages display your content sooner, so your users don’t have to wait for the entire page to load. Commonly referred to as <link>Critical CSS</link>.`,
						'jetpack-boost'
					)}
					vars={externalLinkTemplateVar( criticalCssLink )}
				/>
			</p>

			<p>
				<TemplatedString
					template={__(
						`<b>Boost will automatically generate your Critical CSS</b> whenever you make changes to the HTML or CSS structure of your site.`,
						'jetpack-boost'
					)}
					vars={{
						b: [ 'strong', {}, '' ],
					}}
				/>
			</p>
		</div>

		<div slot="meta" class="jb-feature-toggle__meta">
			<CloudCssMeta
				cssState={$criticalCssState}
				isCloudCssAvailable={$modulesState.cloud_css?.available}
				criticalCssProgress={$criticalCssProgress}
				issues={$criticalCssIssues}
				isFatalError={$isFatalError}
				primaryErrorSet={$primaryErrorSet}
				suggestRegenerate={$suggestRegenerate}
				{regenerateCriticalCss}
			/>
		</div>
	</Module>

	<Module slug="render_blocking_js">
		<h3 slot="title">
			{__( 'Defer Non-Essential JavaScript', 'jetpack-boost' )}
		</h3>
		<p slot="description">
			<TemplatedString
				template={__(
					`Run non-essential JavaScript after the page has loaded so that styles and images can load more quickly. Read more on <link>web.dev</link>.`,
					'jetpack-boost'
				)}
				vars={externalLinkTemplateVar( deferJsLink )}
			/>
		</p>
	</Module>

	<Module slug="lazy_images">
		<h3 slot="title">{__( 'Lazy Image Loading', 'jetpack-boost' )}</h3>
		<p slot="description">
			<TemplatedString
				template={__(
					`Improve page loading speed by only loading images when they are required. Read more on <link>web.dev</link>.`,
					'jetpack-boost'
				)}
				vars={externalLinkTemplateVar( lazyLoadLink )}
			/>
		</p>
		<Notice
			title={__( 'Lazy image loading is going away', 'jetpack-boost' )}
			message={lazyLoadDeprecationMessage}
			actions={[
				{
					label: __( 'Learn more', 'jetpack-boost' ),
					onClick: learnLazyLoadDeprecation,
					isExternalLink: true,
					variant: 'link',
				},
			]}
		/>
	</Module>

	<Module slug="minify_js">
		<h3 slot="title">{__( 'Concatenate JS', 'jetpack-boost' )}</h3>
		<p slot="description">
			{__(
				'Scripts are grouped by their original placement, concatenated and minified to reduce site loading time and reduce the number of requests.',
				'jetpack-boost'
			)}
		</p>
		<div slot="meta">
			<ReactComponent
				this={MinifyMeta}
				datasyncKey="minify_js_excludes"
				inputLabel={__( 'Exclude JS Strings:', 'jetpack-boost' )}
				buttonText={__( 'Exclude JS Strings', 'jetpack-boost' )}
				placeholder={__( 'Comma separated list of JS scripts to exclude', 'jetpack-boost' )}
			/>
		</div>
	</Module>

	<Module slug="minify_css">
		<h3 slot="title">{__( 'Concatenate CSS', 'jetpack-boost' )}</h3>
		<p slot="description">
			{__(
				'Styles are grouped by their original placement, concatenated and minified to reduce site loading time and reduce the number of requests.',
				'jetpack-boost'
			)}
		</p>

		<div slot="meta">
			<ReactComponent
				this={MinifyMeta}
				datasyncKey="minify_css_excludes"
				inputLabel={__( 'Exclude CSS Strings:', 'jetpack-boost' )}
				buttonText={__( 'Exclude CSS Strings', 'jetpack-boost' )}
				placeholder={__( 'Comma separated list of CSS stylesheets to exclude', 'jetpack-boost' )}
			/>
		</div>
	</Module>

	<Module slug="image_cdn">
		<h3 slot="title">{__( 'Image CDN', 'jetpack-boost' )}</h3>
		<p slot="description">
			{__(
				`Deliver images from Jetpack's Content Delivery Network. Automatically resizes your images to an appropriate size, converts them to modern efficient formats like WebP, and serves them from a worldwide network of servers.`,
				'jetpack-boost'
			)}
		</p>

		<div slot="meta">
			<ImageCdnQualitySettings
				bind:quality={$imageCdnQuality}
				isPremium={$premiumFeatures.includes( 'image-cdn-quality' )}
			/>
		</div>
	</Module>

	<div class="settings">
		<Module slug="image_guide">
			<h3 slot="title">{__( 'Image Guide', 'jetpack-boost' )}<span class="beta">Beta</span></h3>
			<p slot="description">
				{__(
					`This feature helps you discover images that are too large. When you browse your site, the image guide will show you an overlay with information about each image's size.`,
					'jetpack-boost'
				)}
			</p>
			<!-- svelte-ignore missing-declaration -->
			{#if false === Jetpack_Boost.site.canResizeImages}
				<ResizingUnavailable />
			{/if}

			<svelte:fragment slot="cta">
				{#if ! $modulesState.image_size_analysis.available}
					<UpgradeCTA
						description={__(
							'Upgrade to scan your site for issues - automatically!',
							'jetpack-boost'
						)}
						{yearlyPricing}
					/>
				{/if}
			</svelte:fragment>
		</Module>

		<Module slug="image_size_analysis" toggle={false}>
			<h3 slot="title">
				{__( 'Image Size Analysis', 'jetpack-boost' )}<span class="beta">Beta</span>
			</h3>
			<p slot="description">
				{__(
					`This tool will search your site for images that are too large and have an impact on your visitors' experience, page loading times, and search rankings. Once finished, it will give you a report of all improperly sized images with suggestions on how to fix them.`,
					'jetpack-boost'
				)}
			</p>

			<svelte:fragment slot="meta">
				{#if $modulesState.image_size_analysis.active}
					<RecommendationsMeta
						isaSummary={$isaSummary}
						isCdnActive={$modulesState.image_cdn.active}
					/>
				{/if}
			</svelte:fragment>
		</Module>
	</div>

	<SuperCacheInfo />
</div>

<style lang="scss">
	.settings {
		border-top: 1px solid hsl( 0, 0%, 90% );
		padding-top: 20px;
	}
	.beta {
		background: var( --jp-green-5 );
		color: var( --jp-green-60 );
		padding: 2px 5px;
		border-radius: 3px;
		font-size: 0.8rem;
		margin-left: 10px;
		transform: translateY( -4.5px );
		display: inline-block;
	}

	[slot='notice'] {
		margin-top: 1rem;
	}
</style>
