// projects/plugins/boost/app/assets/src/js/pages/image-size-analysis/image-size-analysis.tsx
import { __ } from '@wordpress/i18n';
import {
	Hero,
	Pagination,
	Table,
	Tabs,
	getGroupedReports,
	useIsaData,
	useIsaReport,
} from '$features/image-size-analysis';
import Footer from '../../layout/footer/footer';
import Header from '../../layout/header/header';
import { isaGroupKeys } from '$features/image-size-analysis/lib/isa-groups';
import { useNavigate } from 'react-router-dom';

type Props = {
	isImageCdnModuleActive: boolean;
	page: number;
	group: isaGroupKeys;
};

const ImageSizeAnalysis = ( { page, group, isImageCdnModuleActive }: Props ) => {
	const [ isaData ] = useIsaData( page, group );
	const [ isaReport ] = useIsaReport();
	const navigate = useNavigate();
	const dataGroupTabs = isaReport.data ? getGroupedReports( isaReport.data ) : undefined;
	const activeGroupName = group as keyof typeof dataGroupTabs;
	const activeReport =
		dataGroupTabs && activeGroupName ? dataGroupTabs[ activeGroupName ] : undefined;
	return (
		<div id="jb-dashboard" className="jb-dashboard">
			<Header subPageTitle={ __( 'Image analysis report', 'jetpack-boost' ) } />
			<div className="jb-recommendations-page jb-section--alt">
				<div className="jb-container">
					<Hero
						isImageCdnModuleActive={ isImageCdnModuleActive }
						isaLastUpdated={ isaData.data?.last_updated || 0 }
						group={ activeReport }
					/>
					<Tabs
						currentTab={ activeReport }
						activeGroupKey={ group }
						imageDataGroupTabs={ dataGroupTabs }
						setActiveTab={ groupName => {
							navigate( `/image-size-analysis/${ groupName }/1` );
						} }
					/>
				</div>

				<div className="jb-table-wrap">
					<Table
						isaDataLoading={ isaData.isLoading }
						activeGroup={ group }
						images={ isaData.data?.images || [] }
						isaReport={ isaReport.data || undefined }
					/>
				</div>

				<div className="jb-container">
					<Pagination group={ group } current={ page } total={ isaData.data?.total_pages || 1 } />
					<Footer />
				</div>
			</div>
		</div>
	);
};

export default ImageSizeAnalysis;

// projects/plugins/boost/app/assets/src/js/pages/image-size-analysis/ImageSizeAnalysis.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { __ } from '@wordpress/i18n';
	import { Hero } from '$features/image-size-analysis/hero/hero';
	import Pagination from '$features/image-size-analysis/recommendations/pagination/pagination';
	import Table from '$features/image-size-analysis/recommendations/table/table';
	import Tabs from '$features/image-size-analysis/recommendations/tabs/tabs';
	import {
		initializeIsaData,
		isaData,
		isaDataLoading,
	} from '$features/image-size-analysis/lib/stores/isa-data';
	import {
		initializeIsaSummary,
		isaSummary,
		getGroupedSummary,
	} from '$features/image-size-analysis/lib/stores/isa-summary';
	import ReactComponent from '$features/ReactComponent.svelte';
	import Footer from '$layout/footer/footer';
	import Header from '$layout/header/header';
	import { modulesState } from '$lib/stores/modules';
	import { isaGroupLabels } from '$features/image-size-analysis/lib/isa-groups';

	initializeIsaData();
	onMount( initializeIsaSummary );

	$: isImageCdnModuleActive = $modulesState.image_cdn.active;
	$: isaLastUpdated = $isaData.data.last_updated;
	$: images = $isaData.data.images;
	$: activeGroup = dataGroupTabs[ $isaData.query.group ];
	$: dataLoading = $isaDataLoading;
	$: summary = $isaSummary;
	$: dataGroupTabs = getGroupedSummary( $isaSummary ); // the counts are off now
</script>

<div id="jb-dashboard" class="jb-dashboard">
	<ReactComponent this={Header} subPageTitle={__( 'Image analysis report', 'jetpack-boost' )} />
	<div class="jb-recommendations-page jb-section--alt">
		<div class="jb-container">
			<ReactComponent this={Hero} {isImageCdnModuleActive} {isaLastUpdated} group={activeGroup} />
			<ReactComponent
				this={Tabs}
				{activeGroup}
				imageDataGroupTabs={dataGroupTabs}
				{isaGroupLabels}
			/>
		</div>

		<div class="jb-table-wrap">
			<ReactComponent
				this={Table}
				isaDataLoading={dataLoading}
				{activeGroup}
				{images}
				isaSummary={summary}
			/>
		</div>

		<div class="jb-container">
			<ReactComponent
				this={Pagination}
				group={$isaData.query.group}
				current={$isaData.query.page}
				total={$isaData.data.total_pages}
			/>
			<ReactComponent this={Footer} />
		</div>
	</div>
</div>
