// projects/plugins/boost/app/assets/src/js/elements/FoldingElement.svelte
<script lang="ts">
	export let showLabel: string;
	export let hideLabel: string;
	export let visible = false;

	const toggle = () => ( visible = ! visible );
	$: label = visible ? hideLabel : showLabel;
</script>

<button class="components-button is-link foldable-element-control" class:visible on:click={toggle}>
	{label}
</button>

{#if visible}
	<slot />
{/if}

// projects/plugins/boost/app/assets/src/js/react-components/components/folding-element/index.tsx
import { useState } from 'react';

type PropTypes = {
	labelExpandedText: string;
	labelCollapsedText: string;
	isExpanded?: boolean;
	children?: React.ReactNode;
};

const FoldingElement: React.FC< PropTypes > = ( {
	labelExpandedText,
	labelCollapsedText,
	isExpanded = false,
	children = [],
} ) => {
	const [ expanded, setExpanded ] = useState( isExpanded );
	const label = expanded ? labelCollapsedText : labelExpandedText;

	return (
		// <button className="components-button is-link foldable-element-control" class:visible onClick={toggle}>
		<>
			<button
				className="components-button is-link foldable-element-control"
				onClick={ () => setExpanded( ! expanded ) }
			>
				{ label }
			</button>

			{ expanded && <>{ children }</> }
		</>
	);
};

export default FoldingElement;
