// projects/plugins/boost/app/assets/src/js/features/critical-css/critical-css-meta/critical-css-meta.tsx
import { __ } from '@wordpress/i18n';
import Status from '../status/status';
import ShowStopperError from '../show-stopper-error/show-stopper-error';
import ProgressBar from '$features/ui/progress-bar/progress-bar';
import styles from './critical-css-meta.module.scss';
import { useEffect, useState } from '@wordpress/element';
import {
	useCriticalCssState,
	useRegenerateCriticalCssAction,
} from '../lib/stores/critical-css-state';
import { getCriticalCssIssues, isFatalError } from '../lib/critical-css-errors';
import { RegenerateCriticalCssSuggestion, useRegenerationReason } from '..';
import { useLocalCriticalCssGenerator } from '../local-generator/local-generator-provider';

type CriticalCssMetaProps = {
	isCloudCssAvailable: boolean;
};

const CriticalCssMeta: React.FC< CriticalCssMetaProps > = ( { isCloudCssAvailable } ) => {
	const [ hasRetried, setHasRetried ] = useState( false );
	const [ cssState ] = useCriticalCssState();
	const regenerateAction = useRegenerateCriticalCssAction();
	const [ regenerateReason ] = useRegenerationReason();

	const successCount = cssState.providers
		? cssState.providers.filter( provider => provider.status === 'success' ).length
		: 0;

	function retry() {
		setHasRetried( true );
		regenerateAction.mutate();
	}

	const { progress } = useLocalCriticalCssGenerator();

	// On mount, check for not_generated status, and request generation if needed.
	useEffect( () => {
		if ( cssState.status === 'not_generated' ) {
			regenerateAction.mutate();
		}
		// eslint-disable-next-line react-hooks/exhaustive-deps -- Only run on mount.
	}, [] );

	if ( cssState.status === 'pending' ) {
		return (
			<div className="jb-critical-css-progress">
				<div className={ styles[ 'progress-label' ] }>
					{ __(
						'Generating Critical CSS. Please don’t leave this page until completed.',
						'jetpack-boost'
					) }
				</div>
				<ProgressBar progress={ progress || 0 } />
			</div>
		);
	} else if ( isFatalError( cssState ) ) {
		return <ShowStopperError cssState={ cssState } retry={ retry } showRetry={ ! hasRetried } />;
	}

	return (
		<>
			<Status
				isCloudCssAvailable={ isCloudCssAvailable }
				status={ cssState.status }
				issues={ getCriticalCssIssues( cssState ) }
				successCount={ successCount }
				updated={ cssState.updated }
				progress={ progress || 0 }
				showRegenerateButton={ !! regenerateReason }
			/>

			<RegenerateCriticalCssSuggestion regenerateReason={ regenerateReason } />
		</>
	);
};

export default CriticalCssMeta;

// projects/plugins/boost/app/assets/src/js/features/critical-css/CriticalCssMeta.svelte
<script lang="ts">
	import { __ } from '@wordpress/i18n';
	import CriticalCssShowStopperError from './CriticalCssShowStopperError.svelte';
	import CriticalCssStatus from './CriticalCssStatus.svelte';
	import ProgressActivityLabel from './ProgressActivityLabel.svelte';
	import ProgressBar from '$features/ui/ProgressBar.svelte';
	import { CriticalCssState } from '$lib/stores/critical-css-state-types';

	export let cssState: CriticalCssState;
	export let isCloudCssAvailable: boolean;
	export let criticalCssProgress: number;
	export let issues: CriticalCssState[ 'providers' ] = [];
	export let isFatalError: boolean;
	export let primaryErrorSet;
	export let suggestRegenerate;
	export let regenerateCriticalCss;

	$: successCount = cssState.providers.filter( provider => provider.status === 'success' ).length;
</script>

{#if cssState.status === 'pending'}
	<div class="jb-critical-css-progress">
		<ProgressActivityLabel>
			{__(
				'Generating Critical CSS. Please don’t leave this page until completed.',
				'jetpack-boost'
			)}
		</ProgressActivityLabel>
		<ProgressBar progress={criticalCssProgress} />
	</div>
{:else if isFatalError}
	<CriticalCssShowStopperError
		status={cssState.status}
		{primaryErrorSet}
		statusError={cssState.status_error}
		{regenerateCriticalCss}
	/>
{:else}
	<CriticalCssStatus
		{isCloudCssAvailable}
		status={cssState.status}
		{successCount}
		updated={cssState.updated}
		{issues}
		progress={criticalCssProgress}
		{suggestRegenerate}
	/>
{/if}
