// projects/plugins/boost/app/assets/src/js/features/image-size-analysis/recommendations/ui/row-title/row-title.tsx
import React from 'react';
import styles from './row-title.module.scss';

interface RowTitleProps {
	title: string;
	url: string;
}

const RowTitle: React.FC< RowTitleProps > = ( { title, url } ) => {
	const urlWithoutProtocol = url.replace( /^https?:\/\/(www\.)?/, '' );

	return (
		<>
			<b className={ styles.heading } title={ title }>
				{ title }
			</b>
			<a href={ url } target="_blank" rel="noopener noreferrer" className={ styles.link }>
				{ urlWithoutProtocol }
			</a>
		</>
	);
};

export default RowTitle;

// projects/plugins/boost/app/assets/src/js/modules/image-size-analysis/recommendations/components/RowTitle.svelte
<script lang="ts">
	export let title: string;
	export let url: string;

	const urlWithoutProtocol = url.replace( /^https?:\/\/(www\.)?/, '' );
</script>

<b>{title}</b>
<a href={url} target="_blank">
	{urlWithoutProtocol}
</a>

<style lang="scss">
	b {
		display: block;
		font-size: 1.125rem;
		margin-bottom: 4px;
	}

	a {
		font-size: 0.875rem;
		color: var( --gray-80 );
		text-decoration: none;
	}

	a:hover {
		text-decoration: underline;
	}
</style>
