// projects/plugins/boost/app/assets/src/js/react-components/pages/settings/sections/Support.tsx
import { __ } from '@wordpress/i18n';
import { openPaidSupport } from '../../../../utils/paid-plan';

export const Support = () => {
	return (
		<div className="jb-section">
			<div className="jb-container--narrow">
				<div className="jb-support">
					<div className="jb-support__content">
						<h3 className="jb-support__title">{ __( "We're here to help", 'jetpack-boost' ) }</h3>
						<p className="jb-support__description">
							{ __(
								'Your paid plan gives you access to prioritized Jetpack Boost support',
								'jetpack-boost'
							) }
						</p>
					</div>
					<div className="jb-support__cta">
						<button
							className="components-button jb-button jb-button--outline"
							onClick={ openPaidSupport }
							type="button"
						>
							{ __( 'Contact Us', 'jetpack-boost' ) }
						</button>
					</div>
				</div>
			</div>
		</div>
	);
};

// projects/plugins/boost/app/assets/src/js/pages/settings/sections/Support.svelte
<script lang="ts">
	import { __ } from '@wordpress/i18n';
	import { openPaidSupport } from '../../../utils/paid-plan';
</script>

<div class="jb-section">
	<div class="jb-container--narrow">
		<div class="jb-support">
			<div class="jb-support__content">
				<h3 class="jb-support__title">
					{__( "We're here to help", 'jetpack-boost' )}
				</h3>
				<p class="jb-support__description">
					{__(
						'Your paid plan gives you access to prioritized Jetpack Boost support',
						'jetpack-boost'
					)}
				</p>
			</div>
			<div class="jb-support__cta">
				<button
					class="components-button jb-button jb-button--outline"
					on:click={openPaidSupport}
					type="button"
				>
					{__( 'Contact Us', 'jetpack-boost' )}
				</button>
			</div>
		</div>
	</div>
</div>
