// projects/plugins/boost/app/assets/src/js/elements/OtherGroupContext.svelte
<script lang="ts">
	import { __ } from '@wordpress/i18n';
</script>

<div class="jb-score-context">
	<span class="jb-score-context__info-icon">i</span>
	<div class="jb-score-context__info-container">
		<p>
			{__(
				'In addition to the Homepage, Pages and Posts, Boost will also analyze the following custom post types found on your site:',
				'jetpack-boost'
			)}
		</p>
		<ul>
			<!-- svelte-ignore missing-declaration -->
			{#each Object.entries( Jetpack_Boost.site.postTypes ) as [slug, label]}
				<li>{label}</li>
			{/each}
		</ul>
		<i />
	</div>
</div>

<style scope="scss">
	ul {
		list-style: outside;
		margin-left: 20px;
	}

	ul:last-of-type {
		margin-bottom: 0;
	}
</style>

// projects/plugins/boost/app/assets/src/js/features/image-size-analysis/other-group-context/other-group-context.tsx
import { IconTooltip } from '@automattic/jetpack-components';
import { __ } from '@wordpress/i18n';
import styles from './other-group-context.module.scss';

const OtherGroupContext = () => {
	return (
		<IconTooltip
			title=""
			placement={ 'bottom-end' }
			className={ styles.tooltip }
			iconSize={ 18 }
			offset={ 8 }
		>
			<p>
				{ __(
					'In addition to the Homepage, Pages and Posts, Boost will also analyze the following custom post types found on your site:',
					'jetpack-boost'
				) }
			</p>
			<ul>
				{ Object.entries( Jetpack_Boost.site.postTypes ).map( ( [ key, value ] ) => (
					<li key={ key }>{ value }</li>
				) ) }
			</ul>
		</IconTooltip>
	);
};

export default OtherGroupContext;
