// projects/plugins/boost/app/assets/src/js/elements/Price.svelte
<script>
	import { getCurrencyObject } from '@automattic/format-currency';

	export let value;
	export let currency;
	export let isOff;
	export let hidePriceFraction;

	const { symbol, integer, fraction } = getCurrencyObject( value, currency );
	const showPriceFraction = ! hidePriceFraction || ! fraction.endsWith( '00' );
</script>

<p class="jb-price" class:jb-price--not-off-price={! isOff}>
	<sup class="jb-price__symbol">
		{symbol}
	</sup>
	{integer}
	{#if showPriceFraction}
		<sup class="jb-price__fraction">
			<strong>{fraction}</strong>
		</sup>
	{/if}
</p>

// projects/packages/search/src/dashboard/components/price/index.jsx
import { getCurrencyObject } from '@automattic/format-currency';
import { Text } from '@automattic/jetpack-components';
import React from 'react';

/**
 * React component to render a Price composition.
 *
 * @param {object}  props                   - Component props.
 * @param {number}  props.amount            - Amount.
 * @param {string}  props.currency          - Currency code (e.g. 'USD').
 * @param {boolean} props.hidePriceFraction - Whether or not to hide the fraction.
 * @param {string}  props.tag               - Topmost element tag.
 * @return {React.ReactNode} - Price react component.
 */
const Price = ( { amount, currency, hidePriceFraction, tag = 'span' } ) => {
	const { symbol, integer, fraction } = getCurrencyObject( amount, currency );
	const showPriceFraction = ! hidePriceFraction || ! fraction.endsWith( '00' );

	return (
		<Text component={ tag }>
			{ symbol }
			{ integer }
			{ showPriceFraction && fraction }
		</Text>
	);
};

export default Price;
