// projects/plugins/boost/app/assets/src/js/components/back-button/index.tsx
import { __ } from '@wordpress/i18n';
import LeftArrow from '../../svg/left-arrow.svg';
import { navigate } from '../../utils/navigate';

type BackButtonProps = {
	route: string;
};

const BackButton: React.FC< BackButtonProps > = ( { route = '/' } ) => {
	const handleBack = () => {
		navigate( route );
	};

	return (
		<button
			className="components-button components-button--back is-link close"
			onClick={ handleBack }
		>
			<LeftArrow />
			{ __( 'Go back', 'jetpack-boost' ) }
		</button>
	);
};

export default BackButton;

// projects/plugins/boost/app/assets/src/js/elements/BackButton.svelte
<script>
	import LeftArrow from '../svg/left-arrow.svg';
	import routerHistory from '../utils/router-history.ts';
	import { __ } from '@wordpress/i18n';

	const { navigate } = routerHistory;

	export let route = -1;
</script>

<button
	class="components-button components-button--back is-link close"
	on:click={() => navigate( route )}
>
	<LeftArrow />
	{__( 'Go back', 'jetpack-boost' )}
</button>
