// projects/plugins/boost/app/assets/src/js/features/ui/back-button/back-button.tsx
import { __ } from '@wordpress/i18n';
import LeftArrow from '$svg/left-arrow';
import { useNavigate } from 'react-router-dom';

type BackButtonProps = {
	route?: string;
};

const BackButton: React.FC< BackButtonProps > = ( { route = '/' } ) => {
	const navigate = useNavigate();
	const handleBack = () => {
		navigate( route );
	};

	return (
		<button
			className="components-button components-button--back is-link close"
			onClick={ handleBack }
		>
			<LeftArrow />
			{ __( 'Go back', 'jetpack-boost' ) }
		</button>
	);
};

export default BackButton;

// projects/plugins/boost/app/assets/src/js/elements/BackButton.svelte
<script lang="ts">
	import { useNavigate } from 'svelte-navigator';
	import { __ } from '@wordpress/i18n';
	import LeftArrow from '../svg/left-arrow.svg';

	const navigate = useNavigate();

	export let route: number | string = -1;
</script>

<button
	class="components-button components-button--back is-link close"
	on:click={() => navigate( route )}
>
	<LeftArrow />
	{__( 'Go back', 'jetpack-boost' )}
</button>
