// projects/plugins/boost/app/assets/src/js/react-components/components/critical-css-error-description/folding-element/index.tsx
import classNames from 'classnames';
import { useState } from 'react';
import styles from './styles.module.scss';

type PropTypes = {
	labelExpandedText: string;
	labelCollapsedText: string;
	isExpanded?: boolean;
	children?: React.ReactNode;
};

const FoldingElement: React.FC< PropTypes > = ( {
	labelExpandedText,
	labelCollapsedText,
	isExpanded = false,
	children = [],
} ) => {
	const [ expanded, setExpanded ] = useState( isExpanded );
	const label = expanded ? labelCollapsedText : labelExpandedText;

	return (
		<>
			<button
				className={ classNames( 'components-button is-link', styles[ 'foldable-element-control' ], {
					visible: expanded,
				} ) }
				onClick={ () => setExpanded( ! expanded ) }
			>
				{ label }
			</button>

			{ expanded && <div className={ styles[ 'fade-in' ] }>{ children }</div> }
		</>
	);
};

export default FoldingElement;

// projects/plugins/boost/app/assets/src/js/elements/FoldingElement.svelte
<script lang="ts">
	export let showLabel: string;
	export let hideLabel: string;
	export let visible = false;

	const toggle = () => ( visible = ! visible );
	$: label = visible ? hideLabel : showLabel;
</script>

<button class="components-button is-link foldable-element-control" class:visible on:click={toggle}>
	{label}
</button>

{#if visible}
	<slot />
{/if}
