// projects/plugins/boost/app/assets/src/js/react-components/components/critical-css-error-description/numbered-list/index.tsx
import { createInterpolateElement } from '@wordpress/element';
import { type InterpolateVars } from '../../../utils/interplate-vars-types';
import styles from './styles.module.scss';

type NumberedListTypes = {
	items: string[];
	interpolateVars: InterpolateVars;
};

const NumberedList: React.FC< NumberedListTypes > = ( { items, interpolateVars } ) => {
	return (
		<ol className={ styles[ 'numbered-list' ] }>
			{ items.map( ( item, index ) => (
				<li key={ index }>
					<span className={ styles.index }>{ index + 1 }</span>
					<span className={ styles.text }>
						{ createInterpolateElement( item, interpolateVars ) }
					</span>
				</li>
			) ) }
		</ol>
	);
};

export default NumberedList;

// projects/plugins/boost/app/assets/src/js/elements/NumberedList.svelte
<script lang="ts">
	import { TemplateVars } from '../utils/copy-dom-template';
	import TemplatedString from './TemplatedString.svelte';

	/**
	 * List of string items to include in the list.
	 */
	export let items: string[];

	/**
	 * Template vars to fill in <template> elements in each list item.
	 */
	export let vars: TemplateVars;
</script>

<ol class="numbered-list">
	{#each items as item, index}
		<li>
			<span class="index">{index + 1}</span>
			<span class="text">
				<TemplatedString template={item} {vars} />
			</span>
		</li>
	{/each}
</ol>
