// projects/packages/backup/src/js/components/backup-storage-space/storage-addon-upsell-prompt/price.jsx
import { getCurrencyObject } from '@automattic/number-formatters';

const Price = ( { fullPrice, discountedPrice, currency, hidePriceFraction } ) => {
	const finalPrice = discountedPrice > 0 ? discountedPrice : fullPrice;

	const { symbol, integer, fraction } = getCurrencyObject( finalPrice, currency );
	const showPriceFraction = hidePriceFraction === false || ! fraction.endsWith( '00' );
	return (
		<span>
			{ symbol }
			{ integer }
			{ showPriceFraction && fraction }
		</span>
	);
};

export default Price;

// projects/plugins/boost/app/assets/src/js/elements/Price.svelte
<script>
	import { getCurrencyObject } from '@automattic/format-currency';

	export let value;
	export let currency;
	export let isOff;
	export let hidePriceFraction;

	const { symbol, integer, fraction } = getCurrencyObject( value, currency );
	const showPriceFraction = ! hidePriceFraction || ! fraction.endsWith( '00' );
</script>

<p class="jb-price" class:jb-price--not-off-price={! isOff}>
	<sup class="jb-price__symbol">
		{symbol}
	</sup>
	{integer}
	{#if showPriceFraction}
		<sup class="jb-price__fraction">
			<strong>{fraction}</strong>
		</sup>
	{/if}
</p>
