// projects/js-packages/components/components/product-price/index.tsx
import { __ } from '@wordpress/i18n';
import Text from '../text';
import { Price } from './price';
import styles from './style.module.scss';
import type { ProductPriceProps } from './types';
import type React from 'react';

/**
 * React component to render the price.
 *
 * @param {ProductPriceProps} props - Component props.
 * @returns {React.ReactNode} Price react component.
 */
const ProductPrice: React.FC< ProductPriceProps > = ( {
	price,
	offPrice,
	currency = '',
	showNotOffPrice = true,
	promoLabel = '',
	leyend = __( '/month, paid yearly', 'jetpack' ),
	isNotConvenientPrice = false,
	hidePriceFraction = false,
	children,
} ) => {
	if ( ( price == null && offPrice == null ) || ! currency ) {
		return null;
	}

	showNotOffPrice = showNotOffPrice && offPrice != null;

	return (
		<>
			<div className={ styles.container }>
				<Price
					value={ offPrice ?? price }
					currency={ currency }
					isOff={ ! isNotConvenientPrice }
					hidePriceFraction={ hidePriceFraction }
				/>
				{ showNotOffPrice && (
					<Price
						value={ price }
						currency={ currency }
						isOff={ false }
						hidePriceFraction={ hidePriceFraction }
					/>
				) }
				{ promoLabel && <Text className={ styles[ 'promo-label' ] }>{ promoLabel }</Text> }
			</div>
			{ ! children && <Text className={ styles.leyend }>{ leyend }</Text> }
			{ children }
		</>
	);
};

export default ProductPrice;
export * from './price';

// projects/plugins/boost/app/assets/src/js/elements/ProductPrice.svelte
<script>
	import { __ } from '@wordpress/i18n';
	import Price from './Price.svelte';

	export let price;
	export let offPrice;
	export let currency = '';
	export let showNotOffPrice = true;
	export let promoLabel = '';
	export let leyend = __( '/month, paid yearly', 'jetpack-boost' );
	export let isNotConvenientPrice = false;
	export let hidePriceFraction = false;
</script>

<template>
	{#if price !== null && offPrice !== null && currency}
		<div class="jb-price__container">
			<Price
				value={offPrice ?? price}
				{currency}
				isOff={! isNotConvenientPrice}
				{hidePriceFraction}
			/>
			{#if showNotOffPrice && offPrice !== null}
				<Price value={price} {currency} isOff={false} {hidePriceFraction} />
			{/if}
			<p class="jb-price__promo-label">{promoLabel}</p>
		</div>

		<p class="jb-price__leyend">{leyend}</p>
	{/if}
</template>
