// projects/plugins/boost/app/assets/src/js/react-components/recommendation-context/index.tsx
import classNames from 'classnames';
import { ImageCdnRecommendation } from '../image-cdn-recommendation';
import styles from './styles.module.scss';

export const RecommendationContext = () => {
	return (
		<div className={ classNames( styles.wrapper, 'jb-score-context' ) }>
			<span className={ classNames( styles.icon, 'jb-score-context__info-icon' ) }>i</span>
			<div className={ classNames( styles.container, 'jb-score-context__info-container' ) }>
				<ImageCdnRecommendation />
				<i />
			</div>
		</div>
	);
};

// projects/plugins/boost/app/assets/src/js/elements/RecommendationContext.svelte
<script lang="ts">
	import { ImageCdnRecommendation } from '../react-components/image-cdn-recommendation';
	import ReactComponent from './ReactComponent.svelte';
</script>

<div class="jb-score-context">
	<span class="jb-score-context__info-icon">i</span>
	<div class="jb-score-context__info-container">
		<ReactComponent this={ImageCdnRecommendation} />
		<i />
	</div>
</div>

<style lang="scss">
	@use '../../css/main/mixins.scss' as *;

	.jb-score-context {
		top: -4px;
	}

	.jb-score-context__info-container {
		left: -118px;
		min-width: 400px;
	}

	.jb-score-context__info-container i {
		left: 315px;
	}

	.jb-score-context__info-icon {
		margin-left: 0;
	}
</style>
