// projects/plugins/boost/app/assets/src/js/features/critical-css/time-ago/time-ago.tsx
// This Component shows a span with the given time (Date) as a relative time in
// the past. Mouseover to show the exact time.
import describeTimeAgo from '$lib/utils/describe-time-ago';
import { useEffect, useState } from 'react';

const TimeAgo = ( { time } ) => {
	const [ label, setLabel ] = useState( describeTimeAgo( time ) );

	useEffect( () => {
		// Update label every 10 seconds.
		const interval = setInterval( () => {
			setLabel( describeTimeAgo( time ) );
		}, 10 * 1000 );

		return () => clearInterval( interval );
	}, [ time ] );

	return (
		<span title={ time.toLocaleString() } className="time-ago">
			{ label }
		</span>
	);
};

export default TimeAgo;

// projects/plugins/boost/app/assets/src/js/elements/TimeAgo.svelte
<!--
	This Component shows a span with the given time (Date) as a relative time in
	the past. Mouseover to show the exact time.
-->
<script>
	import { readable } from 'svelte/store';
	import describeTimeAgo from '../utils/describe-time-ago.ts';

	export let time;

	const label = readable( describeTimeAgo( time ), set => {
		// Update label every 10 seconds.
		const interval = setInterval( () => {
			set( describeTimeAgo( time ) );
		}, 10000 );

		// Clear interval on store cleanup.
		return () => clearInterval( interval );
	} );
</script>

<span title={time.toLocaleString()} class="time-ago">
	{$label}
</span>
