// projects/plugins/boost/app/assets/src/js/features/image-size-analysis/recommendations/Table.svelte
<script lang="ts">
	import { __ } from '@wordpress/i18n';
	import { type ISA_Data } from '../lib/stores/isa-data';
	import { ISAStatus, type ISASummary } from '../lib/stores/isa-summary';
	import BrokenDataRow from './row-types/BrokenDataRow.svelte';
	import ImageMissingRow from './row-types/ImageMissingRow.svelte';
	import ImageSizeRow from './row-types/ImageSizeRow.svelte';
	import LoadingRow from './row-types/LoadingRow.svelte';
	import Spinner from '$features/ui/Spinner.svelte';
	import TemplatedString from '$features/TemplatedString.svelte';
	import actionLinkTemplateVar from '$lib/utils/action-link-template-var';

	export let needsRefresh: boolean;
	export let refresh: () => Promise< void >;
	export let isaDataLoading: boolean;
	export let activeGroup: string;
	export let images: ISA_Data[];
	export let isaSummary: ISASummary | null;

	let isLoading = false;
	let ignoreStatusUpdated = false;
	async function delayedLoadingUpdate( loading: boolean ) {
		if ( ignoreStatusUpdated ) {
			ignoreStatusUpdated = false;
			return;
		}
		isLoading = loading;
	}
	$: delayedLoadingUpdate( isaDataLoading );

	function getActiveImages( _images: ISA_Data[], loading: boolean ) {
		// Return no rows while loading. The UI will auto-pad it with loading rows.
		if ( loading ) {
			return [];
		}

		// If the user is switching between tabs, we want to show the images that are already loaded
		const filteredImages = _images.filter( image => image.status === activeFilter );
		if ( filteredImages.length === 0 && loading ) {
			return _images;
		}

		// Show filtered images
		return filteredImages;
	}

	$: activeImages = getActiveImages( images, isLoading );
	$: jobFinished = isaSummary?.status === ISAStatus.Completed;
	$: activeFilter = activeGroup === 'ignored' ? 'ignored' : 'active';
</script>

<div class="jb-loading-spinner" class:active={isLoading}>
	<Spinner size="3rem" lineWidth="4px" />
</div>

{#if ! isLoading && activeImages.length === 0}
	<h1>
		{#if needsRefresh}
			<TemplatedString
				template={__(
					'<refresh>Refresh</refresh> to see the latest recommendations.',
					'jetpack-boost'
				)}
				vars={actionLinkTemplateVar( () => refresh(), 'refresh' )}
			/>
		{:else}
			{jobFinished
				? __( '🥳 No image size issues found!', 'jetpack-boost' )
				: __( 'No image size issues found yet…', 'jetpack-boost' )}
		{/if}
	</h1>
{:else}
	<div class="jb-table" class:jb-loading={isLoading}>
		<div class="jb-table-header jb-recommendation-page-grid">
			<div class="jb-table-header__image">Image</div>
			<div class="jb-table-header__potential-size">Potential Size</div>
			<div class="jb-table-header__device">Device</div>
			<div class="jb-table-header__page">Page/Post</div>
		</div>

		{#if isLoading}
			{#each Array( 10 ) as _, i}
				<LoadingRow />
			{/each}
		{:else}
			{#each activeImages as image (image.id)}
				{#if image.type === 'image_size'}
					<ImageSizeRow enableTransition={images.length > 0} details={image} />
				{:else if image.type === 'image_missing'}
					<ImageMissingRow enableTransition={images.length > 0} details={image} />
				{:else}
					<BrokenDataRow />
				{/if}
			{/each}
		{/if}
	</div>
{/if}

// projects/plugins/boost/app/assets/src/js/features/image-size-analysis/recommendations/table/table.tsx
import type React from 'react';
import { __ } from '@wordpress/i18n';
import { useState, useEffect } from 'react';
import BrokenDataRow from '../row-types/broken-data-row/broken-data-row';
import ImageMissingRow from '../row-types/image-missing-row/image-missing-row';
import ImageSizeRow from '../row-types/image-size-row/image-size-row';
import LoadingRow from '../row-types/loading-row/loading-row';
import Spinner from '$features/ui/spinner/spinner';
import type { ISA_Data } from '../../lib/stores/isa-data';
import { ISASummary, ISAStatus } from '../../lib/stores/isa-summary';
import classnames from 'classnames';

interface TableProps {
	refresh: () => Promise< void >;
	isaDataLoading: boolean;
	activeGroup: string;
	images: ISA_Data[];
	isaSummary: ISASummary | null;
}

const Table: React.FC< TableProps > = ( { isaDataLoading, activeGroup, images, isaSummary } ) => {
	const [ isLoading, setIsLoading ] = useState( false );
	const [ activeImages, setActiveImages ] = useState< ISA_Data[] >( [] );
	const [ jobFinished, setJobFinished ] = useState( false );

	useEffect( () => {
		setIsLoading( isaDataLoading );
		setJobFinished( isaSummary?.status === ISAStatus.Completed );
		setActiveImages( images );
	}, [ isaDataLoading, activeGroup, images, isaSummary ] );

	return (
		<>
			<div className={ classnames( 'jb-loading-spinner', { 'jb-active': isLoading } ) }>
				<Spinner size="3rem" lineWidth="4px" />
			</div>

			{ ! isLoading && activeImages.length === 0 ? (
				<h1>
					{ jobFinished
						? __( '🥳 No image size issues found!', 'jetpack-boost' )
						: __( 'No image size issues found yet…', 'jetpack-boost' ) }
				</h1>
			) : (
				<div className={ classnames( 'jb-table', { 'jb-loading': isLoading } ) }>
					<div className="jb-table-header jb-recommendation-page-grid">
						<div className="jb-table-header__image">Image</div>
						<div className="jb-table-header__potential-size">Potential Size</div>
						<div className="jb-table-header__device">Device</div>
						<div className="jb-table-header__page">Page/Post</div>
					</div>

					{ isLoading
						? [ ...Array( 10 ) ].map( ( _, i ) => <LoadingRow key={ i } /> )
						: activeImages.map( image =>
								image.type === 'image_size' ? (
									<ImageSizeRow
										key={ image.id }
										enableTransition={ images.length > 0 }
										details={ image }
									/>
								) : image.type === 'image_missing' ? (
									<ImageMissingRow
										key={ image.id }
										enableTransition={ images.length > 0 }
										details={ image }
									/>
								) : (
									<BrokenDataRow key={ image.id } />
								)
						  ) }
				</div>
			) }
		</>
	);
};

export default Table;
