// projects/plugins/boost/app/assets/src/js/pages/getting-started/getting-started.tsx
import { useState } from 'react';
import { Snackbar } from '@wordpress/components';
import { initializeConnection, getUpgradeURL } from '$lib/stores/connection';
import { recordBoostEvent } from '$lib/utils/analytics';
import { navigate } from '$lib/utils/navigate';
import { BoostPricingTable } from '$features/boost-pricing-table/boost-pricing-table';
import ActivateLicense from '$features/activate-license/activate-license';
import Footer from '$layout/footer/footer';
import Header from '$layout/header/header';
import styles from './getting-started.module.scss';
import { useConfig } from '$lib/stores/config-ds';
import { DataSyncProvider } from '@automattic/jetpack-react-data-sync-client';

type GettingStartedProps = {
	userConnected: boolean;
	isPremium: boolean;
	domain: string;
};

const GettingStarted: React.FC< GettingStartedProps > = ( {
	userConnected,
	isPremium,
	domain,
} ) => {
	const [ selectedPlan, setSelectedPlan ] = useState< 'free' | 'premium' | false >( false );
	const [ snackbarMessage, setSnackbarMessage ] = useState< string >( '' );

	const { pricing } = useConfig();

	async function initialize(
		plan: 'free' | 'premium',
		isPremiumValue: boolean,
		domainValue: string,
		userConnectedValue: boolean
	) {
		setSelectedPlan( plan );

		try {
			// Make sure there is a Jetpack connection
			await initializeConnection();

			// Record this selection. This must be done after the connection is initialized.
			// Possible Events:
			// * free_cta_from_getting_started_page_in_plugin
			// * premium_cta_from_getting_started_page_in_plugin
			await recordBoostEvent( `${ plan }_cta_from_getting_started_page_in_plugin`, {} );

			// Go to the purchase flow if the user doesn't have a premium plan.
			if ( ! isPremiumValue && plan === 'premium' ) {
				window.location.href = getUpgradeURL( domainValue, userConnectedValue );
			} else {
				// Otherwise go to dashboard home.
				// @todo - fix when react routing
				// navigate( '/', { replace: true } );
				navigate( '/' );
			}
		} catch ( e ) {
			// Display the error in a snackbar message
			setSnackbarMessage( e.message || 'Unknown error occurred during the plan selection.' );
		}
	}

	return (
		<div id="jb-dashboard" className="jb-dashboard jb-dashboard--main">
			<Header>
				<ActivateLicense />
			</Header>

			<div className="jb-section jb-section--alt">
				<div className="jb-container">
					<div className={ styles[ 'pricing-table' ] }>
						<BoostPricingTable
							pricing={ pricing }
							onPremiumCTA={ () => initialize( 'premium', isPremium, domain, userConnected ) }
							onFreeCTA={ () => initialize( 'free', isPremium, domain, userConnected ) }
							chosenFreePlan={ selectedPlan === 'free' }
							chosenPaidPlan={ selectedPlan === 'premium' }
						/>
						{ snackbarMessage !== '' && (
							<Snackbar children={ snackbarMessage } onDismiss={ () => setSnackbarMessage( '' ) } />
						) }
					</div>
				</div>
			</div>

			<Footer />
		</div>
	);
};

export default ( props: GettingStartedProps ) => {
	return (
		<DataSyncProvider>
			<GettingStarted { ...props } />
		</DataSyncProvider>
	);
};

// projects/plugins/boost/app/assets/src/js/routes/getting-started/GettingStarted.svelte
<script lang="ts">
	import React from 'react';
	import { Snackbar } from '@wordpress/components';
	import { BoostPricingTable } from './BoostPricingTable/BoostPricingTable';
	import ActivateLicense from '$features/ActivateLicense/ActivateLicense';
	import ReactComponent from '$features/ReactComponent.svelte';
	import Footer from '$layout/Footer/Footer';
	import Header from '$layout/Header/Header';
	import { initializeConnection, getUpgradeURL } from '$lib/stores/connection';
	import { recordBoostEvent } from '$lib/utils/analytics';

	// svelte-ignore unused-export-let - Ignored values supplied by svelte-navigator.
	export let navigate, location;
	export let userConnected: boolean;
	export let pricing: ( typeof Jetpack_Boost )[ 'pricing' ];
	export let isPremium: boolean;
	export let domain: string;

	let snackbarMessage: string;
	let selectedPlan: 'free' | 'premium' | false = false;
	$: if ( selectedPlan !== false ) {
		initialize( selectedPlan );
	}

	async function initialize( plan: 'free' | 'premium' ) {
		try {
			// Make sure there is a Jetpack connection
			await initializeConnection();

			// Record this selection. This must be done after the connection is initialized.
			// Possible Events:
			// * free_cta_from_getting_started_page_in_plugin
			// * premium_cta_from_getting_started_page_in_plugin
			recordBoostEvent( `${ plan }_cta_from_getting_started_page_in_plugin`, {} );

			// Go to the purchase flow if the user doesn't have a premium plan.
			if ( ! isPremium && plan === 'premium' ) {
				window.location.href = getUpgradeURL( domain, userConnected );
			}
			// Otherwise go to dashboard home.
			navigate( '/', { replace: true } );
		} catch ( e ) {
			// Display the error in a snackbar message
			snackbarMessage = e.message || 'Unknown error occurred during the plan selection.';
		} finally {
			selectedPlan = false;
		}
	}

	const activateLicense = React.createElement( ActivateLicense );
</script>

<div id="jb-dashboard" class="jb-dashboard jb-dashboard--main">
	<ReactComponent this={Header} children={activateLicense} />

	<div class="jb-section jb-section--alt">
		<div class="jb-container">
			<div class="jb-pricing-table">
				<ReactComponent
					this={BoostPricingTable}
					{pricing}
					onPremiumCTA={() => ( selectedPlan = 'premium' )}
					onFreeCTA={() => ( selectedPlan = 'free' )}
					chosenFreePlan={selectedPlan === 'free'}
					chosenPaidPlan={selectedPlan === 'premium'}
				/>
				{#if snackbarMessage}
					<ReactComponent
						this={Snackbar}
						children={snackbarMessage}
						onDismiss={() => ( snackbarMessage = '' )}
					/>
				{/if}
			</div>
		</div>
	</div>

	<ReactComponent this={Footer} />
</div>

<style lang="scss">
	.jb-pricing-table {
		isolation: isolate;
	}
</style>
