// projects/plugins/boost/app/assets/src/js/layout/settings-page/settings-page.tsx
import SpeedScore from '$features/speed-score/speed-score';
import Footer from '$layout/footer/footer';
import Header from '$layout/header/header';
import { criticalCssStateCreated, isGenerating } from '$features/critical-css';
import { hasPrioritySupport } from '$lib/utils/paid-plan';
import Support from './support/support';
import Tips from './tips/tips';
import { useSingleModuleState } from '$features/module/lib/stores';
import { useEffect, useState } from 'react';
import classNames from 'classnames';
import styles from './settings-page.module.scss';

type SettingsPageProps = {
	children: React.ReactNode;
};

const SettingsPage = ( { children }: SettingsPageProps ) => {
	const [ isGeneratingValue, setIsGeneratingValue ] = useState( false );
	const [ performanceHistoryState ] = useSingleModuleState( 'performance_history' );

	useEffect( () => {
		const unsubscribe = isGenerating.subscribe( value => {
			setIsGeneratingValue( value );
		} );

		return () => {
			unsubscribe();
		};
	}, [] );

	return (
		<div id="jb-dashboard" className="jb-dashboard jb-dashboard--main">
			<Header />

			<div className="jb-section jb-section--alt jb-section--scores">
				<SpeedScore
					criticalCssCreated={ criticalCssStateCreated }
					criticalCssIsGenerating={ isGeneratingValue }
					performanceHistoryNeedsUpgrade={ ! performanceHistoryState?.available }
				/>
			</div>

			{ children && (
				<div className={ classNames( 'jb-section jb-section--main', styles.section ) }>
					{ children }
				</div>
			) }

			<Tips />

			{ hasPrioritySupport && <Support /> }

			<Footer />
		</div>
	);
};

export default SettingsPage;

// projects/plugins/boost/app/assets/src/js/components/SettingsPage.svelte
<script lang="ts">
	import Score from '../pages/settings/sections/Score.svelte';
	import Tips from '../pages/settings/sections/Tips.svelte';
	import Footer from '../sections/footer';
	import Header from '../sections/Header.svelte';
	import Support from '../sections/support';
	import { hasPrioritySupport } from '../utils/paid-plan';
	import { criticalCssState, isGenerating } from '../stores/critical-css-state';
	import ReactComponent from '../elements/ReactComponent.svelte';
	import { modulesState } from '../stores/modules';

	$: criticalCssCreated = $criticalCssState.created;
	$: criticalCssIsGenerating = $isGenerating;
	$: activeModules = Object.entries( $modulesState ).reduce( ( acc, [ key, value ] ) => {
		if ( key !== 'image_guide' && key !== 'image_size_analysis' ) {
			acc.push( value.active );
		}
		return acc;
	}, [] );
</script>

<div id="jb-dashboard" class="jb-dashboard jb-dashboard--main">
	<Header />

	<div class="jb-section jb-section--alt jb-section--scores">
		<Score {activeModules} {criticalCssCreated} {criticalCssIsGenerating} />
	</div>

	<slot />

	<Tips />

	{#if $hasPrioritySupport}
		<ReactComponent this={Support} />
	{/if}

	<ReactComponent this={Footer} />
</div>
