// projects/plugins/boost/app/assets/src/js/elements/Price.svelte
<script>
	import { getCurrencyObject } from '@automattic/format-currency';

	export let value;
	export let currency;
	export let isOff;
	export let hidePriceFraction;

	const { symbol, integer, fraction } = getCurrencyObject( value, currency );
	const showPriceFraction = ! hidePriceFraction || ! fraction.endsWith( '00' );
</script>

<p class="jb-price" class:jb-price--not-off-price={! isOff}>
	<sup class="jb-price__symbol">
		{symbol}
	</sup>
	{integer}
	{#if showPriceFraction}
		<sup class="jb-price__fraction">
			<strong>{fraction}</strong>
		</sup>
	{/if}
</p>

// projects/js-packages/components/components/product-price/price.tsx
import { getCurrencyObject } from '@automattic/format-currency';
import classnames from 'classnames';
import Text from '../text';
import styles from './style.module.scss';
import type { PriceProps } from './types';
import type React from 'react';

/**
 * React component to render a Price composition.
 *
 * @param {PriceProps} props  - Component props.
 * @returns {React.ReactNode} -Price react component.
 */
export const Price: React.FC< PriceProps > = ( { value, currency, isOff, hidePriceFraction } ) => {
	const classNames = classnames( styles.price, {
		[ styles[ 'is-not-off-price' ] ]: ! isOff,
	} );

	const { symbol, integer, fraction } = getCurrencyObject( value, currency );
	const showPriceFraction = ! hidePriceFraction || ! fraction.endsWith( '00' );

	return (
		<Text className={ classNames } variant="headline-medium" component="p">
			<Text component="sup" variant="title-medium">
				{ symbol }
			</Text>
			{ integer }
			{ showPriceFraction && (
				<Text component="sup" variant="title-medium">
					{ fraction }
				</Text>
			) }
		</Text>
	);
};
