// projects/plugins/boost/app/assets/src/js/features/image-size-analysis/recommendations/row-types/image-size-row/image-size-row.tsx
import React from 'react';
import TableRow from '../table-row/table-row';
import { ImageDataType } from '../../../lib/stores/zod-types';
import Button from '../../../button/button';
import Device from '../../ui/device/device';
import Pill from '../../ui/pill/pill';
import RowTitle from '../../ui/row-title/row-title';
import Thumbnail from '../../ui/thumbnail/thumbnail';
import { __ } from '@wordpress/i18n';
import TableRowHover from '../table-row-hover/table-row-hover';
import { removeGetParams } from '$lib/utils/remove-get-params';
import { recordBoostEventAndRedirect } from '$lib/utils/analytics';

interface ImageSizeRowProps {
	enableTransition: boolean;
	details: ImageDataType;
}

const ImageSizeRow: React.FC< ImageSizeRowProps > = ( { enableTransition, details } ) => {
	const title = details.image.url.split( '/' ).pop();

	const potentialSavings = Math.max(
		0,
		Math.min( details.image.weight.current - 2, details.image.weight.potential )
	);
	const potentialSize =
		potentialSavings > 0 ? Math.round( details.image.weight.current - potentialSavings ) : '?';
	const currentSize = details.image.weight.current;
	const sizeDifference = ( potentialSavings / currentSize ) * 100;
	const pillColor = sizeDifference <= 30 ? '#f5e5b3' : '#facfd2';
	return (
		<TableRow enableTransition={ enableTransition } expandable={ true }>
			<Main
				title={ title }
				details={ details }
				potentialSize={ potentialSize }
				pillColor={ pillColor }
			/>
			<Expanded details={ details } />
		</TableRow>
	);
};

export default ImageSizeRow;

interface MainProps {
	title: string;
	details: ImageDataType;
	potentialSize: number | string;
	pillColor: string;
}

const Main: React.FC< MainProps > = ( { title, pillColor, details, potentialSize } ) => {
	return (
		<div>
			<div className="jb-table-row__thumbnail">
				<Thumbnail title={ title } url={ details.image.url } width={ 65 } height={ 65 } />
			</div>

			<div className="jb-table-row__title">
				<RowTitle title={ removeGetParams( title ) } url={ details.page.url } />
			</div>

			<div className="jb-table-row__potential-size">
				<Pill color={ pillColor }>{ Math.round( details.image.weight.current ) } KB</Pill>

				<div className="jb-arrow">→</div>

				<Pill color="#d0e6b8">{ potentialSize } KB</Pill>
			</div>

			<div className="jb-table-row__hover-content">
				<TableRowHover
					details={ details }
					device_type={ details.device_type }
					edit_url={ details.page.edit_url }
					instructions={ details.instructions }
				/>
			</div>

			<div className="jb-table-row__device">
				<Device device={ details.device_type } />
			</div>

			<div className="jb-table-row__page">
				<a href={ details.page.url } className="jb-page__link">
					{ details.page.title }
				</a>
			</div>
		</div>
	);
};

interface ExpandedProps {
	details: ImageDataType;
	pillColor: string;
	potentialSize: number;
}

const Expanded: React.FC< ExpandedProps > = ( { details, pillColor, potentialSize } ) => {
	return (
		<>
			<div className="jb-expanded-info jb-mobile-only">
				<h4 className="jb-expanded-info__header">{ __( 'Potential Size', 'jetpack-boost' ) }</h4>
				<div className="jb-pills">
					<Pill color={ pillColor }>{ Math.round( details.image.weight.current ) } KB</Pill>
					<div className="jb-arrow">→</div>
					<Pill color="#d0e6b8">{ potentialSize } KB</Pill>
				</div>
			</div>

			<div className="jb-expanded-info jb-mobile-only">
				<h4 className="jb-expanded-info__header">{ __( 'Device', 'jetpack-boost' ) }</h4>
				<div className="jb-expanded-icon">
					<Device device={ details.device_type } />
				</div>
				<span className="jb-expanded-info__text">
					{ details.device_type === 'desktop'
						? __( 'This issue affects large screens', 'jetpack-boost' )
						: __( 'This issue affects small screens', 'jetpack-boost' ) }
				</span>
			</div>

			<div className="jb-expanded-info jb-image-details">
				<h4 className="jb-expanded-info__header">{ __( 'Image Details', 'jetpack-boost' ) }</h4>
				<div className="jb-expanded-info__row">
					<div className="jb-label">{ __( 'File Dimensions', 'jetpack-boost' ) }</div>
					<div className="jb-value">
						{ Math.round( details.image.dimensions.file.width ) }x
						{ Math.round( details.image.dimensions.file.height ) }
						px
					</div>
				</div>
				<div className="jb-expanded-info__row">
					<div className="jb-label">{ __( 'Expected Dimensions', 'jetpack-boost' ) }</div>
					<div className="jb-value">
						{ Math.round( details.image.dimensions.expected.width ) }x
						{ Math.round( details.image.dimensions.expected.height ) }
						px
					</div>
				</div>
				<div className="jb-expanded-info__row">
					<div className="jb-label">{ __( 'Size on screen', 'jetpack-boost' ) }</div>
					<div className="jb-value">
						{ Math.round( details.image.dimensions.size_on_screen.width ) }x
						{ Math.round( details.image.dimensions.size_on_screen.height ) }
						px
					</div>
				</div>
			</div>

			<div className="jb-expanded-info jb-fix-options">
				<h4 className="jb-expanded-info__header">{ __( 'How to fix', 'jetpack-boost' ) }</h4>
				<p className="jb-expanded-info__text">{ details.instructions }</p>
				{ details.page.edit_url && (
					<div className="jb-actions">
						<Button
							width="auto"
							fill
							onClick={ () =>
								recordBoostEventAndRedirect(
									details.page.edit_url,
									'clicked_fix_on_page_on_isa_report',
									{ device_type: details.device_type }
								)
							}
						>
							{ __( 'Fix on page', 'jetpack-boost' ) }
						</Button>
					</div>
				) }
			</div>
		</>
	);
};

// projects/plugins/boost/app/assets/src/js/features/image-size-analysis/recommendations/row-types/ImageSizeRow.svelte
<script lang="ts">
	import { __ } from '@wordpress/i18n';
	import TableRow from './TableRow.svelte';
	import TableRowHover from './TableRowHover.svelte';
	import type { ImageDataType } from '../../lib/stores/zod-types';
	import Button from '../../Button.svelte';
	import Device from '../ui/Device.svelte';
	import Pill from '../ui/Pill.svelte';
	import RowTitle from '../ui/RowTitle.svelte';
	import Thumbnail from '../ui/Thumbnail.svelte';
	import { recordBoostEventAndRedirect } from '$lib/utils/analytics';
	import { removeGetParams } from '$lib/utils/remove-get-params';

	export let enableTransition: boolean;
	export let details: ImageDataType;

	const title = details.image.url.split( '/' ).pop();
	const currentSize = details.image.weight.current;
	const potentialSavings = Math.max(
		0,
		Math.min( currentSize - 2, details.image.weight.potential )
	);
	const potentialSize = potentialSavings > 0 ? Math.round( currentSize - potentialSavings ) : '?';

	const sizeDifference = ( potentialSavings / currentSize ) * 100;
	const pillColor = sizeDifference <= 30 ? '#f5e5b3' : '#facfd2';
</script>

<TableRow {enableTransition} expandable={true}>
	<svelte:fragment slot="main">
		<div class="jb-table-row__thumbnail">
			<Thumbnail {title} url={details.image.url} width={65} height={65} />
		</div>

		<div class="jb-table-row__title">
			<RowTitle title={removeGetParams( title )} url={details.page.url} />
		</div>

		<div class="jb-table-row__potential-size">
			<Pill color={pillColor}>
				{Math.round( details.image.weight.current )} KB
			</Pill>

			<div class="jb-arrow">→</div>

			<Pill color="#d0e6b8">
				{potentialSize} KB
			</Pill>
		</div>

		<div class="jb-table-row__hover-content">
			<TableRowHover
				{details}
				device_type={details.device_type}
				edit_url={details.page.edit_url}
				instructions={details.instructions}
			/>
		</div>

		<div class="jb-table-row__device">
			<Device device={details.device_type} />
		</div>

		<div class="jb-table-row__page">
			<a href={details.page.url} class="jb-page__link">{details.page.title}</a>
		</div>
	</svelte:fragment>

	<svelte:fragment slot="expanded">
		<div class="jb-expanded-info jb-mobile-only">
			<h4 class="jb-expanded-info__header">{__( 'Potential Size', 'jetpack-boost' )}</h4>

			<div class="jb-pills">
				<Pill color={pillColor}>
					{Math.round( details.image.weight.current )} KB
				</Pill>

				<div class="jb-arrow">→</div>

				<Pill color="#d0e6b8">
					{potentialSize} KB
				</Pill>
			</div>
		</div>

		<div class="jb-expanded-info jb-mobile-only">
			<h4 class="jb-expanded-info__header">{__( 'Device', 'jetpack-boost' )}</h4>

			<div class="jb-expanded-icon">
				<Device device={details.device_type} />
			</div>

			<span class="jb-expanded-info__text">
				{details.device_type === 'desktop'
					? __( 'This issue affects large screens', 'jetpack-boost' )
					: __( 'This issue affects small screens', 'jetpack-boost' )}
			</span>
		</div>

		<div class="jb-expanded-info jb-image-details">
			<h4 class="jb-expanded-info__header">{__( 'Image Details', 'jetpack-boost' )}</h4>

			<div class="jb-expanded-info__row">
				<div class="jb-label">
					{__( 'File Dimensions', 'jetpack-boost' )}
				</div>
				<div class="jb-value">
					{Math.round( details.image.dimensions.file.width )}
					x
					{Math.round( details.image.dimensions.file.height )}
					px
				</div>
			</div>

			<div class="jb-expanded-info__row">
				<div class="jb-label">
					{__( 'Expected Dimensions', 'jetpack-boost' )}
				</div>
				<div class="jb-value">
					{Math.round( details.image.dimensions.expected.width )}
					x
					{Math.round( details.image.dimensions.expected.height )}
					px
				</div>
			</div>

			<div class="jb-expanded-info__row">
				<div class="jb-label">
					{__( 'Size on screen', 'jetpack-boost' )}
				</div>
				<div class="jb-value">
					{Math.round( details.image.dimensions.size_on_screen.width )}
					x
					{Math.round( details.image.dimensions.size_on_screen.height )}
					px
				</div>
			</div>
		</div>

		<div class="jb-expanded-info jb-fix-options">
			<h4 class="jb-expanded-info__header">
				{__( 'How to fix', 'jetpack-boost' )}
			</h4>
			<p class="jb-expanded-info__text">{details.instructions}</p>
			{#if details.page.edit_url}
				<div class="jb-actions">
					<Button
						width="auto"
						fill
						on:click={() =>
							recordBoostEventAndRedirect(
								details.page.edit_url,
								'clicked_fix_on_page_on_isa_report',
								{ device_type: details.device_type }
							)}
					>
						{__( 'Fix on page', 'jetpack-boost' )}
					</Button>
				</div>
			{/if}
		</div>
	</svelte:fragment>
</TableRow>
