// projects/plugins/boost/app/assets/src/js/pages/settings/elements/UrlComponentsExample.svelte
<script lang="ts">
	import { __ } from '@wordpress/i18n';

	const protocol = window.location.protocol.split( ':' )[ 0 ];
	const hostname = window.location.hostname;
</script>

<div class="url-container">
	<div class="segment">
		<div class="label">{__( 'Protocol', 'jetpack-boost' )}</div>

		<div class="arrows" />

		{protocol}
	</div>
	<div class="segment">://</div>
	<div class="segment">
		<div class="label">{__( 'Host name', 'jetpack-boost' )}</div>

		<div class="arrows" />

		{hostname}
	</div>
</div>

// projects/plugins/boost/app/assets/src/js/features/critical-css/url-components-example/url-components-example.tsx
import { __ } from '@wordpress/i18n';

const UrlComponentsExample = () => {
	const protocol = window.location.protocol.split( ':' )[ 0 ];
	const hostname = window.location.hostname;

	return (
		<div className="url-container">
			<div className="segment">
				<div className="label">{ __( 'Protocol', 'jetpack-boost' ) }</div>

				<div className="arrows" />

				{ protocol }
			</div>
			<div className="segment">://</div>
			<div className="segment">
				<div className="label">{ __( 'Host name', 'jetpack-boost' ) }</div>

				<div className="arrows" />

				{ hostname }
			</div>
		</div>
	);
};

export default UrlComponentsExample;
