// projects/plugins/boost/app/assets/src/js/react-components/sections/header/index.tsx
import React from 'react';
import { navigate } from '../../../utils/navigate';
import BackButton from '../../components/back-button';
import ChevronRight from '../../svg/chevron-right';
import Logo from '../../svg/logo';

interface HeaderProps {
	subPageTitle?: string;
	children?: React.ReactNode;
}

const Header = ( { subPageTitle = '', children }: HeaderProps ) => {
	return (
		<div className="jb-dashboard-header">
			<div className="jb-container masthead">
				<div className="nav-area">
					<button className="jb-dashboard-header__logo" onClick={ () => navigate( '/' ) }>
						<Logo />
					</button>

					{ subPageTitle !== '' && (
						<>
							<div className="chevron">
								<ChevronRight />
							</div>
							<div className="subpage">{ subPageTitle }</div>
						</>
					) }
				</div>

				{ children }
			</div>

			{ subPageTitle !== '' && (
				<div className="jb-container back-button">
					<BackButton />
				</div>
			) }
		</div>
	);
};

export default Header;

// projects/plugins/boost/app/assets/src/js/components/sections/Header.svelte
<script lang="ts">
	import { useNavigate } from 'svelte-navigator';
	import BackButton from '../BackButton/BackButton';
	import ReactComponent from '../ReactComponent.svelte';
	import ChevronRight from '../../svg/chevron-right.svg';
	import Logo from '../../svg/logo.svg';

	const navigate = useNavigate();

	export let subPage: string | null = null;
</script>

<div class="jb-dashboard-header">
	<div class="jb-container masthead">
		<div class="nav-area">
			<!-- svelte-ignore a11y-click-events-have-key-events -->
			<div class="jb-dashboard-header__logo" on:click={() => navigate( '/' )}>
				<Logo />
			</div>

			{#if subPage}
				<div class="chevron">
					<ChevronRight />
				</div>

				<div class="subpage">
					{subPage}
				</div>
			{/if}
		</div>

		<slot />
	</div>

	{#if subPage}
		<div class="jb-container back-button">
			<ReactComponent this={BackButton} />
		</div>
	{/if}
</div>

<style lang="scss">
	.jb-dashboard-header {
		background-color: var( --primary-white );
	}

	.masthead {
		display: flex;
		justify-content: space-between;
		margin-top: 40px;
		margin-bottom: 20px;
		align-items: center;
		flex-wrap: wrap;
		gap: 24px;
	}

	.nav-area {
		display: flex;
		align-items: center;
		flex-direction: row;

		.jb-dashboard-header__logo {
			cursor: pointer;

			:global( svg ) {
				height: 42px;
				width: 100%;
			}
		}

		.chevron {
			margin-left: 16px;
			margin-right: 16px;
			width: 24px;
			height: 24px;
			padding-top: 2px;
			text-align: center;
		}

		.subpage {
			color: var( --gray-40 );
			font-size: 16px;
			margin-top: -2px;
		}
	}
</style>
