// projects/plugins/boost/app/assets/src/js/features/image-size-analysis/recommendations/row-types/broken-data-row/broken-data-row.tsx
import { __ } from '@wordpress/i18n';
import TableRow from '../table-row/table-row';

const BrokenDataRow: React.FC = () => {
	return (
		<TableRow enableTransition={ false } expandable={ false }>
			<div className="jb-table-row-title">
				{ __( 'An error occurred while loading this entry.', 'jetpack-boost' ) }
			</div>
		</TableRow>
	);
};

export default BrokenDataRow;

// projects/plugins/boost/app/assets/src/js/modules/image-size-analysis/recommendations/row-types/BrokenDataRow.svelte
<script lang="ts">
	import { __ } from '@wordpress/i18n';
	import TableRow from './TableRow.svelte';
</script>

<TableRow enableTransition={false} expandable={false}>
	<svelte:fragment slot="main">
		<div class="jb-table-row__title">
			{__( 'An error occurred while loading this entry.', 'jetpack-boost' )}
		</div>
	</svelte:fragment>
</TableRow>

<style lang="scss">
	.jb-table-row__title {
		grid-column: title;
	}
</style>
