// projects/plugins/boost/app/assets/src/js/features/image-size-analysis/recommendations/row-types/table-row/table-row.tsx
import React, { useState, useCallback } from 'react';

interface TableRowProps {
	expandable: boolean;
	enableTransition: boolean;
	children: React.ReactNode;
	expandedContent: React.ReactNode;
}

const TableRow: React.FC< TableRowProps > = ( {
	expandable,
	enableTransition,
	children,
	expandedContent,
} ) => {
	const [ expanded, setExpanded ] = useState( false );

	const toggleExpand = useCallback(
		( e: React.MouseEvent< HTMLDivElement > ) => {
			if ( ! expandable ) {
				return;
			}

			// Don't expand if the user clicked a link or a button.
			if ( e.target instanceof HTMLAnchorElement || e.target instanceof HTMLButtonElement ) {
				return;
			}

			setExpanded( ! expanded );
		},
		[ expandable, expanded ]
	);

	const transitionDuration = enableTransition ? 250 : 0;
	const transitionStyle = {
		transition: `height ${ transitionDuration }ms ease-out`,
	};

	return (
		<div
			className={ `jb-table-row-container ${ expanded ? 'expanded' : '' }` }
			style={ transitionStyle }
		>
			{ /* eslint-disable-next-line jsx-a11y/no-static-element-interactions, jsx-a11y/click-events-have-key-events */ }
			<div className="jb-table-row jb-recommendation-page-grid" onClick={ toggleExpand }>
				{ children }

				{ expandable && <div className="jb-table-row__expand">{ /* SVG goes here */ }</div> }
			</div>

			{ expanded && expandable && (
				<div className="jb-table-row__expanded">{ expandedContent }</div>
			) }
		</div>
	);
};

export default TableRow;

// projects/plugins/boost/app/assets/src/js/modules/image-size-analysis/recommendations/row-types/TableRow.svelte
<script lang="ts">
	import { quadOut } from 'svelte/easing';
	import { slide } from 'svelte/transition';

	export let expandable: boolean;
	export let enableTransition: boolean;

	let expanded = false;
	function toggleExpand( e ) {
		if ( ! expandable ) {
			return;
		}

		// Don't expand if the user clicked a link or a button.
		if ( e.target.tagName === 'A' || e.target.tagName === 'BUTTON' ) {
			return;
		}
		expanded = ! expanded;
	}
</script>

<!-- svelte-ignore a11y-click-events-have-key-events -->
<div
	class="jb-table-row-container"
	out:slide={{ duration: enableTransition ? 250 : 0, easing: quadOut }}
	class:expanded
>
	<div class="jb-table-row jb-recommendation-page-grid" on:click={toggleExpand}>
		<slot name="main" />

		{#if expandable}
			<!-- svelte-ignore a11y-click-events-have-key-events -->
			<div class="jb-table-row__expand">
				<svg
					width="16"
					height="10"
					viewBox="0 0 16 10"
					fill="none"
					xmlns="http://www.w3.org/2000/svg"
				>
					<path
						d="M0.667349 1.33325L8.00068 7.99992L15.334 1.33325"
						stroke="#1E1E1E"
						stroke-width="1.5"
					/>
				</svg>
			</div>
		{/if}
	</div>

	{#if expanded && expandable}
		<div class="jb-table-row__expanded">
			<slot name="expanded" />
		</div>
	{/if}
</div>
