// projects/plugins/boost/app/assets/src/js/features/activate-license/activate-license.tsx
import { ExternalLink } from '@wordpress/components';
import { createInterpolateElement } from '@wordpress/element';
import { __ } from '@wordpress/i18n';
import styles from './activate-license.module.scss';
import { isWoaHosting } from '$lib/utils/hosting';

const ActivateLicense = () => {
	if ( isWoaHosting() ) {
		return null;
	}

	const activateLicenseUrl = 'admin.php?page=my-jetpack#/add-license';

	return (
		<p className={ styles[ 'activate-license' ] }>
			{ createInterpolateElement(
				__(
					'Already have an existing plan or license key? <link>Click here to get started</link>',
					'jetpack-boost'
				),
				{
					link: <ExternalLink className={ styles.link } href={ activateLicenseUrl } />,
				}
			) }
		</p>
	);
};

export default ActivateLicense;

// projects/plugins/boost/app/assets/src/js/pages/benefits/ActivateLicense.svelte
<script lang="ts">
	import { __ } from '@wordpress/i18n';
	import TemplatedString from '../../elements/TemplatedString.svelte';
</script>

<p class="jb-activate-license">
	<TemplatedString
		template={__(
			'Already have an existing plan or license key? <link>Click here to get started</link>',
			'jetpack-boost'
		)}
		vars={{
			link: [
				'a',
				{
					class: 'jb-activate-license__link',
					href: 'admin.php?page=my-jetpack#/add-license',
				},
			],
		}}
	/>
</p>

<style lang="scss">
	.jb-activate-license {
		font-size: 13px;

		:global( .jb-activate-license__link ) {
			color: var( --blue-50 );

			&:hover,
			&:active {
				color: var( --blue-60 );
			}
		}
	}
</style>
