// projects/plugins/boost/app/assets/src/js/routes/index/CollapsibleMeta.svelte
<script lang="ts">
	import PencilIcon from '../../../../static/images/pencil.svg';
	import CloseIcon from '../../svg/close.svg';

	export let editText: string;
	export let closeEditText: string;

	let isEditing = false;
</script>

<div class="jb-collapsible-meta">
	<header class="jb-collapsible-meta__header">
		<slot name="header" />
		<button
			type="button"
			class="jb-collapsible-meta__edit-button components-button is-link"
			on:click={() => {
				isEditing = ! isEditing;
			}}
		>
			{#if isEditing}
				<CloseIcon class="edit-icon" />
				{closeEditText}
			{:else}
				<PencilIcon class="edit-icon" />
				{editText}
			{/if}
		</button>
	</header>

	{#if isEditing}
		<slot />
	{:else}
		<div class="summary">
			<slot name="summary" />
		</div>
	{/if}
</div>

<style lang="scss">
	@use '../../../css/main/variables.scss' as *;

	.jb-collapsible-meta {
		margin-top: 2em;

		&__header {
			display: flex;
			justify-content: space-between;
			align-items: center;
			margin-bottom: 1em;
			@media screen and ( max-width: 530px ) {
				flex-direction: column;
				align-items: flex-start;
			}
		}

		&__edit-button {
			padding: 4px;
		}

		.summary {
			color: $gray-40;
			font-size: 14px;
			line-height: 22px;
		}
	}

	:global( .jb-collapsible-meta__edit-button .edit-icon ) {
		margin: 4px 4px 2px 0;
	}
</style>

// projects/plugins/boost/app/assets/src/js/features/image-cdn/collapsible-meta/collapsible-meta.tsx
import styles from './collapsible-meta.module.scss';
import { Button } from '@automattic/jetpack-components';
import React, { useState } from 'react';
import CloseIcon from '$svg/close';
import PencilIcon from '$svg/pencil';

type CollapsibleMetaProps = {
	children: React.ReactNode;
	header: React.ReactNode;
	summary: React.ReactNode;
	editText: string;
	closeEditText: string;
};

const CollapsibleMeta = ( {
	children,
	header,
	summary,
	editText,
	closeEditText,
}: CollapsibleMetaProps ) => {
	const [ isEditing, setIsEditing ] = useState( false );
	return (
		<div className={ styles[ 'collapsible-meta' ] }>
			<header className={ styles.header }>
				{ header }
				<Button
					variant="link"
					size="small"
					icon={
						isEditing ? (
							<CloseIcon className={ styles[ 'edit-icon' ] } />
						) : (
							<PencilIcon className={ styles[ 'edit-icon' ] } />
						)
					}
					className={ styles[ 'edit-button' ] }
					onClick={ () => {
						setIsEditing( ! isEditing );
					} }
				>
					{ isEditing ? closeEditText : editText }
				</Button>
			</header>

			{ isEditing ? children : <div className={ styles.summary }>{ summary }</div> }
		</div>
	);
};

export default CollapsibleMeta;
