// projects/plugins/boost/app/assets/src/js/features/ImageSizeAnalysis/recommendations/RowTypes/TableRowHover.svelte
<script lang="ts">
	import { __ } from '@wordpress/i18n';
	import Button from '../../components/Button.svelte';
	import { recordBoostEventAndRedirect } from '$lib/utils/analytics';
	export let edit_url: string | null = null;
	export let instructions: string;
	export let device_type: string | null = null;
</script>

<div class="jb-row-hover">
	<p class="jb-row-hover__instruction">{instructions}</p>

	{#if edit_url}
		<div class="jb-row-hover__button-container">
			<Button
				small
				fill
				on:click={() =>
					recordBoostEventAndRedirect( edit_url, 'clicked_edit_page_on_isa_report', {
						device_type,
					} )}
			>
				{__( 'Edit Page', 'jetpack-boost' )}
			</Button>
		</div>
	{/if}
</div>

// projects/plugins/boost/app/assets/src/js/features/image-size-analysis/recommendations/row-types/table-row-hover/table-row-hover.tsx
import React from 'react';
import { __ } from '@wordpress/i18n';
import Button from '$features/image-size-analysis/button/button';
import { recordBoostEventAndRedirect } from '$lib/utils/analytics';
import { type IsaImage } from '$features/image-size-analysis';

// @TODO: Move this to a DataSync Store.
const __DEV_ENABLE_FIX_BUTTON = true;

interface TableRowHoverProps {
	imageId?: IsaImage[ 'id' ];
	edit_url?: string;
	instructions: string;
	device_type: string | null;
	isFixed?: boolean;
	toggleImageFix?: ( imageId: IsaImage[ 'id' ] ) => void;
}

const TableRowHover: React.FC< TableRowHoverProps > = ( {
	imageId,
	edit_url,
	instructions,
	device_type,
	isFixed,
	toggleImageFix,
} ) => {
	return (
		<div className="jb-row-hover">
			<p className="jb-row-hover__instruction">{ instructions }</p>

			{ edit_url && (
				<div className="jb-row-hover__button-container">
					{ __DEV_ENABLE_FIX_BUTTON && imageId && toggleImageFix && device_type === 'desktop' ? (
						<Button width="auto" fill onClick={ () => toggleImageFix( imageId ) }>
							{ isFixed ? __( 'Undo Fix', 'jetpack-boost' ) : __( 'Fix', 'jetpack-boost' ) }
						</Button>
					) : (
						<Button
							small
							fill
							onClick={ () =>
								recordBoostEventAndRedirect( edit_url, 'clicked_edit_page_on_isa_report', {
									device_type: device_type || 'unknown',
								} )
							}
						>
							{ __( 'Edit Page', 'jetpack-boost' ) }
						</Button>
					) }
				</div>
			) }
		</div>
	);
};

export default TableRowHover;
