// projects/plugins/boost/app/assets/src/js/modules/image-size-analysis/recommendations/row-types/TableRowHover.svelte
<script lang="ts">
	import { __ } from '@wordpress/i18n';
	import api from '../../../../api/api';
	import Button from '../../../../elements/Button.svelte';
	import config from '../../../../stores/config';
	import { recordBoostEvent, recordBoostEventAndRedirect } from '../../../../utils/analytics';
	import type { ImageDataType } from '../../store/zod-types';
	export let edit_url: string | null;
	export let instructions: string;
	export let device_type: string;
	export let details: ImageDataType;

	async function fixImageSize() {
		let post_id = '0';
		if ( details.page.edit_url ) {
			const url = new URL( details.page.edit_url );
			post_id = new URLSearchParams( url.search ).get( 'post' );
		} else {
			post_id = '0';
		}

		const data = {
			image_url: details.image.url,
			image_width: details.image.dimensions.expected.width.toString(),
			image_height: details.image.dimensions.expected.height.toString(),
			post_id,
			nonce: Jetpack_Boost.fixImageNonce,
			fix: ! details.image.fixed,
		};
		const response = await api.post( '/image-size-analysis/fix', data );
		if ( response.status === 'success' ) {
			if ( response.changed === 'fix' ) {
				recordBoostEvent( 'isa_fix_image_success', {} );
				details.image.fixed = true;
			} else {
				recordBoostEvent( 'isa_undo_fix_image_success', {} );
				details.image.fixed = false;
			}
		} else {
			recordBoostEvent( 'isa_fix_image_failure', {} );
		}
	}

	function handleFixClick() {
		recordBoostEvent( 'isa_fix_image', {} );
		return fixImageSize();
	}
</script>

<div class="jb-row-hover">
	<p class="jb-row-hover__instruction">{instructions}</p>

	{#if edit_url}
		<div class="jb-row-hover__button-container">
			{#if $config.isaFixButton && device_type === 'desktop'}
				<Button width="auto" fill on:click={() => handleFixClick()}>
					{details.image.fixed ? __( 'Undo Fix', 'jetpack-boost' ) : __( 'Fix', 'jetpack-boost' )}
				</Button>
			{:else}
				<Button
					small
					fill
					on:click={() =>
						recordBoostEventAndRedirect( edit_url, 'clicked_edit_page_on_isa_report', {
							device_type,
						} )}
				>
					{__( 'Edit Page', 'jetpack-boost' )}
				</Button>
			{/if}
		</div>
	{/if}
</div>

// projects/plugins/boost/app/assets/src/js/features/image-size-analysis/recommendations/row-types/table-row-hover/table-row-hover.tsx
import React, { useState, useCallback } from 'react';
import { __ } from '@wordpress/i18n';
import Button from '$features/image-size-analysis/button/button';
import { recordBoostEvent, recordBoostEventAndRedirect } from '$lib/utils/analytics';
import type { ImageDataType } from '../../../lib/stores/zod-types';
import api from '$lib/api/api';
import config from '$lib/stores/config';

interface TableRowHoverProps {
	editUrl: string | null;
	instructions: string;
	deviceType: string | null;
	details: ImageDataType;
}

const TableRowHover: React.FC< TableRowHoverProps > = ( {
	editUrl,
	instructions,
	deviceType,
	details,
} ) => {
	const [ imageDetails, setImageDetails ] = useState( details );

	const fixImageSize = useCallback( async () => {
		let postId = '0';
		if ( imageDetails.page.editUrl ) {
			const url = new URL( imageDetails.page.editUrl );
			postId = new URLSearchParams( url.search ).get( 'post' ) || '0';
		}

		const data = {
			imageUrl: imageDetails.image.url,
			imageWidth: imageDetails.image.dimensions.expected.width.toString(),
			imageHeight: imageDetails.image.dimensions.expected.height.toString(),
			postId,
			nonce: Jetpack_Boost.fixImageNonce,
			fix: ! imageDetails.image.fixed,
		};

		const response = await api.post( '/image-size-analysis/fix', data );
		if ( response.status === 'success' ) {
			const updatedDetails = { ...imageDetails };
			if ( response.changed === 'fix' ) {
				recordBoostEvent( 'isa_fix_image_success', {} );
				updatedDetails.image.fixed = true;
			} else {
				recordBoostEvent( 'isa_undo_fix_image_success', {} );
				updatedDetails.image.fixed = false;
			}
			setImageDetails( updatedDetails );
		} else {
			recordBoostEvent( 'isa_fix_image_failure', {} );
		}
	}, [ imageDetails ] );

	const handleFixClick = useCallback( () => {
		recordBoostEvent( 'isa_fix_image', {} );
		fixImageSize();
	}, [ fixImageSize ] );

	return (
		<div className="jb-row-hover">
			<p className="jb-row-hover__instruction">{ instructions }</p>

			{ editUrl && (
				<div className="jb-row-hover__button-container">
					{ config.isaFixButton && deviceType === 'desktop' ? (
						<Button width="auto" fill onClick={ handleFixClick }>
							{ imageDetails.image.fixed
								? __( 'Undo Fix', 'jetpack-boost' )
								: __( 'Fix', 'jetpack-boost' ) }
						</Button>
					) : (
						<Button
							small
							fill
							onClick={ () =>
								recordBoostEventAndRedirect( editUrl, 'clicked_edit_page_on_isa_report', {
									deviceType,
								} )
							}
						>
							{ __( 'Edit Page', 'jetpack-boost' ) }
						</Button>
					) }
				</div>
			) }
		</div>
	);
};

export default TableRowHover;
