// projects/plugins/boost/app/assets/src/js/components/sections/Footer/Footer.tsx
import { __ } from '@wordpress/i18n';
import AutomatticLogo from '../../../svg/automattic';
import JetpackLogo from '../../../svg/jetpack';
import styles from './Footer.module.scss';

const Footer = () => {
	return (
		<footer className="jb-dashboard-footer">
			<div className={ styles[ 'signature--jetpack' ] }>
				<JetpackLogo />
				{ __( 'Jetpack Boost', 'jetpack-boost' ) }
			</div>
			<div className={ styles[ 'signature--automattic' ] }>
				<a
					href="https://automattic.com"
					aria-label={ __( 'An Automattic Airline', 'jetpack-boost' ) }
				>
					<AutomatticLogo />
				</a>
			</div>
		</footer>
	);
};

export default Footer;

// projects/plugins/boost/app/assets/src/js/sections/Footer.svelte
<script lang="ts">
	import { __ } from '@wordpress/i18n';
	import AutomatticLogo from '../svg/automattic.svg';
	import JetpackIcon from '../svg/jetpack.svg';
</script>

<footer class="jb-dashboard-footer">
	<div class="jb-signature--jetpack">
		<JetpackIcon />
		{__( 'Jetpack Boost', 'jetpack-boost' )}
	</div>
	<div class="jb-signature--automattic">
		<a href="https://automattic.com" aria-label={__( 'An Automattic Airline', 'jetpack-boost' )}>
			<AutomatticLogo />
		</a>
	</div>
</footer>
