// projects/plugins/boost/app/assets/src/js/main.tsx
import {
	createHashRouter,
	redirect,
	RouterProvider,
	useLocation,
	useParams,
} from 'react-router-dom';
import Upgrade from './pages/upgrade/upgrade';
import Index from './pages/index';
import AdvancedCriticalCss from './pages/critical-css-advanced/critical-css-advanced';
import GettingStarted from './pages/getting-started/getting-started';
import PurchaseSuccess from './pages/purchase-success/purchase-success';
import SettingsPage from '$layout/settings-page/settings-page';
import React, { useEffect } from 'react';
import { recordBoostEvent } from '$lib/utils/analytics';
import { DataSyncProvider } from '@automattic/jetpack-react-data-sync-client';
import { useGettingStarted } from '$lib/stores/getting-started';
import { useSingleModuleState } from '$features/module/lib/stores';
import ImageSizeAnalysis from './pages/image-size-analysis/image-size-analysis';
import { isaGroupKeys } from '$features/image-size-analysis/lib/isa-groups';
import '../css/admin-style.scss';
import CacheDebugLog from './pages/cache-debug-log/cache-debug-log';

const useBoostRouter = () => {
	const { shouldGetStarted } = useGettingStarted();
	const [ isaState ] = useSingleModuleState( 'image_size_analysis' );

	const checkForGettingStarted = () => {
		if ( shouldGetStarted ) {
			return redirect( '/getting-started' );
		}
		return null;
	};

	return createHashRouter( [
		{
			path: '*',
			loader: checkForGettingStarted,
			element: (
				<SettingsPage>
					<Tracks>
						<Index />
					</Tracks>
				</SettingsPage>
			),
		},
		{
			path: '/cache-debug-log',
			loader: checkForGettingStarted,
			element: (
				<Tracks>
					<CacheDebugLog />
				</Tracks>
			),
		},
		{
			path: '/critical-css-advanced',
			loader: checkForGettingStarted,
			element: (
				<SettingsPage>
					<Tracks>
						<AdvancedCriticalCss />
					</Tracks>
				</SettingsPage>
			),
		},
		{
			path: 'image-size-analysis/:group/:page',
			loader: () => {
				if ( ! isaState?.available ) {
					return redirect( '/' );
				}
				return null;
			},
			element: (
				<Tracks>
					<ISAPage />
				</Tracks>
			),
		},
		{
			path: '/upgrade',
			element: (
				<Tracks>
					<Upgrade />
				</Tracks>
			),
		},
		{
			path: '/getting-started',
			element: (
				<Tracks>
					<GettingStarted />
				</Tracks>
			),
		},
		{
			path: '/purchase-successful',
			element: (
				<Tracks>
					<PurchaseSuccess />
				</Tracks>
			),
		},
	] );
};

function Main() {
	const router = useBoostRouter();
	return <RouterProvider router={ router } />;
}

/**
 * Track the page view.
 *
 * @param props
 * @param props.children - The actual page to render
 */
const Tracks = ( { children }: { children: React.JSX.Element } ) => {
	const location = useLocation();

	useEffect( () => {
		let path = location.pathname.replace( /[-/]/g, '_' );
		if ( path === '_' ) {
			path = '_settings';
		}

		recordBoostEvent( `page_view${ path }`, {
			path: location.pathname,
		} );
	}, [ location ] );

	return children;
};

const ISAPage = () => {
	const { group, page } = useParams< { group: string; page: string } >();
	const [ imageCdnState ] = useSingleModuleState( 'image_cdn' );
	return (
		<ImageSizeAnalysis
			isImageCdnModuleActive={ !! imageCdnState?.active }
			group={ group as isaGroupKeys }
			page={ parseInt( page || '1', 10 ) }
		/>
	);
};

export default () => {
	return (
		<React.StrictMode>
			<DataSyncProvider>
				<Main />
			</DataSyncProvider>
		</React.StrictMode>
	);
};

// projects/plugins/boost/app/assets/src/js/Main.svelte
<script lang="ts">
	import ReactComponent from './components/ReactComponent.svelte';
	import Redirect from './components/Redirect.svelte';
	import SettingsPage from './layouts/SettingsPage/SettingsPage.svelte';
	import AdvancedCriticalCss from './routes/critical-css-advanced/CriticalCssAdvanced.svelte';
	import GettingStarted from './routes/getting-started/GettingStarted.svelte';
	import RecommendationsPage from './routes/image-size-analysis/ImageSizeAnalysis.svelte';
	import Index from './routes/index/Index.svelte';
	import PurchaseSuccess from './routes/purchase-success/PurchaseSuccess';
	import Upgrade from './routes/upgrade/Upgrade.svelte';
	import config from '$lib/stores/config';
	import { connection } from '$lib/stores/connection';
	import { criticalCssIssues } from '$lib/stores/critical-css-state-errors';
	import { modulesState } from '$lib/stores/modules';
	import { recordBoostEvent } from '$lib/utils/analytics';
	import debounce from '$lib/utils/debounce';
	import { Route, Router } from '$lib/utils/router';
	import routerHistory from '$lib/utils/router-history';

	routerHistory.listen(
		debounce( history => {
			// Event names must conform to the following regex: ^[a-z_][a-z0-9_]*$
			let path = history.location.pathname.replace( /[-/]/g, '_' );
			if ( path === '_' ) {
				path = '_settings';
			}

			recordBoostEvent( `page_view${ path }`, {
				path: history.location.pathname,
			} );
		}, 10 )
	);

	$: pricing = $config.pricing;

	$: siteDomain = $config.site.domain;
	$: userConnected = $connection.userConnected;
	$: isPremium = $config.isPremium;
	$: isImageGuideActive = $modulesState.image_guide.active;
	$: isImageSizeAnalysisAvailable = $modulesState.image_size_analysis.available;
	$: isImageSizeAnalysisActive = $modulesState.image_size_analysis.active;

	$: shouldGetStarted = ! $connection.connected && $config.site.online;
</script>

<Router history={routerHistory}>
	<Route path="upgrade" let:location let:navigate>
		<Upgrade {location} {navigate} {pricing} {siteDomain} {userConnected} />
	</Route>

	<Route
		path="getting-started"
		component={GettingStarted}
		{userConnected}
		{pricing}
		{isPremium}
		domain={siteDomain}
	/>

	<Route path="purchase-successful">
		<ReactComponent this={PurchaseSuccess} {isImageGuideActive} />
	</Route>

	<Route path="critical-css-advanced">
		<Redirect when={shouldGetStarted} to="/getting-started">
			<SettingsPage>
				<AdvancedCriticalCss issues={$criticalCssIssues} />
			</SettingsPage>
		</Redirect>
	</Route>

	<Route path="/">
		<Redirect when={shouldGetStarted} to="/getting-started">
			<SettingsPage>
				<Index />
			</SettingsPage>
		</Redirect>
	</Route>

	{#if isImageSizeAnalysisAvailable && isImageSizeAnalysisActive}
		<Route path="image-size-analysis/:group/:page" component={RecommendationsPage} />
	{/if}
</Router>

<style lang="scss">
	.jb-section--main {
		z-index: 14;
	}
</style>
