// projects/plugins/boost/app/assets/src/js/routes/image-size-analysis/Hero/Hero.tsx
import { IconTooltip } from '@automattic/jetpack-components';
import classNames from 'classnames';
import { createInterpolateElement } from '@wordpress/element';
import { __, _n, sprintf } from '@wordpress/i18n';
import styles from './Hero.module.scss';
import ImageCdnRecommendation from '$components/ImageCdnRecommendation/ImageCdnRecommendation';

// removed in:fade={{ duration: 300, easing: quadOut }} from .jb-hero

export const Hero = ( {
	needsRefresh,
	refresh,
	isImageCdnModuleActive,
	isaLastUpdated,
	hasActiveGroup,
	totalIssueCount,
} ) => {
	const formatter = new Intl.DateTimeFormat( 'en-US', {
		month: 'long',
		day: 'numeric',
		hour: 'numeric',
		minute: 'numeric',
		hour12: true,
	} );

	const lastUpdated = formatter.format( isaLastUpdated );
	const showLatestReport = hasActiveGroup && !! isaLastUpdated;

	return (
		<>
			{ showLatestReport ? (
				<div className={ classNames( styles.hero, styles[ 'fade-in' ] ) }>
					<span>Latest report as of { lastUpdated }</span>
					{ totalIssueCount > 0 && (
						<h1>
							{ sprintf(
								/* translators: %d: number of image recommendations */
								_n(
									'%d Image Recommendation',
									'%d Image Recommendations',
									totalIssueCount,
									'jetpack-boost'
								),
								totalIssueCount
							) }

							{ ! isImageCdnModuleActive && totalIssueCount > 0 && (
								<IconTooltip
									title=""
									placement={ 'bottom' }
									className={ styles.tooltip }
									iconSize={ 22 }
									offset={ 20 }
									wide={ true }
								>
									<ImageCdnRecommendation />
								</IconTooltip>
							) }
						</h1>
					) }

					{ needsRefresh && (
						<span>
							{ createInterpolateElement(
								__(
									'More recommendations have been found. <refresh>Refresh</refresh> to see the latest recommendations.',
									'jetpack-boost'
								),
								{
									refresh: (
										// eslint-disable-next-line jsx-a11y/anchor-has-content, jsx-a11y/anchor-is-valid
										<a
											className="action"
											onClick={ event => {
												event.preventDefault();

												refresh();
											} }
											href="#"
										/>
									),
								}
							) }
						</span>
					) }
				</div>
			) : (
				<>
					<span>&nbsp;</span>
					<h1>&nbsp;</h1>
				</>
			) }
		</>
	);
};

// projects/plugins/boost/app/assets/src/js/modules/image-size-analysis/recommendations/Hero.svelte
<script lang="ts">
	import { quadOut } from 'svelte/easing';
	import { fade } from 'svelte/transition';
	import { __, _n, sprintf } from '@wordpress/i18n';
	import RecommendationContext from '../../../elements/RecommendationContext.svelte';
	import TemplatedString from '../../../elements/TemplatedString.svelte';
	import { modulesState } from '../../../stores/modules';
	import actionLinkTemplateVar from '../../../utils/action-link-template-var';
	import { isaData } from '../store/isa-data';
	import { imageDataActiveGroup } from '../store/isa-summary';

	export let needsRefresh: boolean;
	export let refresh: () => Promise< void >;

	const formatter = new Intl.DateTimeFormat( 'en-US', {
		month: 'long',
		day: 'numeric',
		hour: 'numeric',
		minute: 'numeric',
		hour12: true,
	} );
</script>

{#if $imageDataActiveGroup && $isaData.data.last_updated}
	{@const  lastUpdated = formatter.format( $isaData.data.last_updated ) }

	<div class="jb-hero" in:fade={{ duration: 300, easing: quadOut }}>
		<span>Latest report as of {lastUpdated}</span>
		{#if $imageDataActiveGroup.issue_count}
			<h1>
				{sprintf(
					/* translators: %d: number of image recommendations */
					_n(
						'%d Image Recommendation',
						'%d Image Recommendations',
						$imageDataActiveGroup.issue_count,
						'jetpack-boost'
					),
					$imageDataActiveGroup.issue_count
				)}

				{#if ! $modulesState.image_cdn.active && $imageDataActiveGroup.issue_count > 0}
					<RecommendationContext />
				{/if}
			</h1>
		{/if}

		{#if needsRefresh}
			<TemplatedString
				template={__(
					'More recommendations have been found. <refresh>Refresh</refresh> to see the latest recommendations.',
					'jetpack-boost'
				)}
				vars={actionLinkTemplateVar( () => refresh(), 'refresh' )}
			/>
		{/if}
	</div>
{:else}
	<div class="jb-hero">
		<span>&nbsp;</span>
		<h1>&nbsp;</h1>
	</div>
{/if}

<style lang="scss">
	.jb-hero {
		padding: 50px 0 30px;
		display: flex;
		flex-direction: column;
		gap: calc( var( --gap ) / 2 );
	}
</style>
